# Generated by Django 5.2.4 on 2025-08-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Company_name',
            field=models.CharField(default='companyC', max_length=100),
            preserve_default=False,
        ),
    ]
