# Generated by Django 5.2.4 on 2025-08-07 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0002_company_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='cnic_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d{1}$', message='CNIC must be in the format 12345-1234567-1')]),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='cnic_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d{1}$', message='CNIC must be in the format 12345-1234567-1')]),
        ),
    ]
