# Generated by Django 5.2.4 on 2025-08-07 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0003_alter_dealer_cnic_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerrequest',
            name='cnic_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d{1}$', message='CNIC must be in the format 12345-1234567-1')]),
        ),
    ]
