# Generated by Django 5.2.4 on 2025-08-11 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0004_alter_dealerrequest_cnic_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='description',
        ),
        migrations.RemoveField(
            model_name='region',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='region',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='address',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='email',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='description',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='name',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='territory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='FieldAdvisoryService.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='FieldAdvisoryService.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FieldAdvisoryService.company'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_regions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='territory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_territories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='territory',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FieldAdvisoryService.zone'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_zones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zone',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FieldAdvisoryService.region'),
        ),
    ]
