# Generated by Django 5.2.4 on 2025-08-11 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0005_remove_region_created_at_remove_region_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='name',
            field=models.CharField(default='dummy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='territory',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='territory',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='territories', to='FieldAdvisoryService.zone'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='FieldAdvisoryService.region'),
        ),
    ]
