# Generated by Django 5.2.4 on 2025-08-21 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FieldAdvisoryService", "0006_region_name_territory_name_zone_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="regions",
                to="FieldAdvisoryService.company",
            ),
        ),
    ]
