# Generated by Django 5.2.4 on 2025-09-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FieldAdvisoryService", "0008_dealer_user_alter_dealer_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dealer",
            name="email",
        ),
    ]
