# Generated by Django 5.2.4 on 2025-09-03 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FieldAdvisoryService", "0009_remove_dealer_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="dealer",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_user_dealer"
            ),
        ),
    ]
