# Generated by Django 5.2.4 on 2025-09-04 04:27

import FieldAdvisoryService.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FieldAdvisoryService", "0010_dealer_unique_user_dealer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealer",
            name="cnic_back_image",
            field=models.ImageField(
                upload_to="dealers/cnic_back/",
                validators=[FieldAdvisoryService.validators.validate_image],
            ),
        ),
        migrations.AlterField(
            model_name="dealer",
            name="cnic_front_image",
            field=models.ImageField(
                upload_to="dealers/cnic_front/",
                validators=[FieldAdvisoryService.validators.validate_image],
            ),
        ),
    ]
