# Generated by Django 5.2.4 on 2025-09-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FieldAdvisoryService", "0012_alter_dealer_cnic_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealer",
            name="card_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
