# Generated by Django 5.2.4 on 2025-09-22 11:01

import FieldAdvisoryService.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FieldAdvisoryService", "0013_dealer_card_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="territory",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[FieldAdvisoryService.validators.validate_latitude],
            ),
        ),
        migrations.AddField(
            model_name="territory",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[FieldAdvisoryService.validators.validate_longitude],
            ),
        ),
    ]
