# Generated by Django 5.2.4 on 2025-11-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0014_territory_latitude_territory_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerrequest',
            name='sap_card_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='sap_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='sap_response_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
