# Generated by Django 5.2.4 on 2025-12-02 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0015_dealerrequest_sap_card_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sales Order', 'verbose_name_plural': 'Sales Orders'},
        ),
        migrations.AddField(
            model_name='salesorder',
            name='address',
            field=models.TextField(blank=True, help_text='Billing address', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='card_code',
            field=models.CharField(blank=True, help_text='Customer code (BP Code)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='card_name',
            field=models.CharField(blank=True, help_text='Customer name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='comments',
            field=models.TextField(blank=True, help_text='Order comments/remarks', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='contact_person_code',
            field=models.IntegerField(blank=True, help_text='Contact person code', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='doc_currency',
            field=models.CharField(default='PKR', help_text='Document currency', max_length=10),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='doc_date',
            field=models.DateField(blank=True, help_text='Document date', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='doc_due_date',
            field=models.DateField(blank=True, help_text='Document due date', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='doc_object_code',
            field=models.CharField(default='oOrders', help_text='Document object code', max_length=50),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='doc_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Exchange rate', max_digits=10),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='doc_type',
            field=models.CharField(choices=[('dDocument_Items', 'Items'), ('dDocument_Service', 'Service')], default='dDocument_Items', max_length=50),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='federal_tax_id',
            field=models.CharField(blank=True, help_text='Customer NTN/Tax ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_posted_to_sap',
            field=models.BooleanField(default=False, help_text='Posted to SAP successfully'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='pay_to_code',
            field=models.IntegerField(blank=True, help_text='Pay to code', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='posted_at',
            field=models.DateTimeField(blank=True, help_text='When posted to SAP', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sap_doc_entry',
            field=models.IntegerField(blank=True, help_text='SAP Document Entry (after posting)', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sap_doc_num',
            field=models.IntegerField(blank=True, help_text='SAP Document Number (after posting)', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sap_error',
            field=models.TextField(blank=True, help_text='SAP error message if posting failed', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='series',
            field=models.IntegerField(default=8, help_text='Series number for document'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='summery_type',
            field=models.CharField(choices=[('dNoSummary', 'No Summary'), ('dSummary', 'Summary')], default='dNoSummary', max_length=50),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tax_date',
            field=models.DateField(blank=True, help_text='Tax date', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='u_crje',
            field=models.CharField(blank=True, help_text='CRJE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='u_s_card_code',
            field=models.CharField(blank=True, help_text='Child Customer Code', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='u_s_card_name',
            field=models.CharField(blank=True, help_text='Child Customer Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='u_secje',
            field=models.CharField(blank=True, help_text='SECJE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='u_sotyp',
            field=models.CharField(blank=True, help_text='Sales Order Type', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='u_swje',
            field=models.CharField(blank=True, help_text='SWJE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='u_usid',
            field=models.CharField(blank=True, help_text='Portal User ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FieldAdvisoryService.dealer'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FieldAdvisoryService.meetingschedule'),
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_num', models.IntegerField(help_text='Line number in order')),
                ('item_code', models.CharField(help_text='Item code', max_length=50)),
                ('item_description', models.CharField(help_text='Item description', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity', max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price', max_digits=15)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount %', max_digits=5)),
                ('warehouse_code', models.CharField(help_text='Warehouse code', max_length=50)),
                ('vat_group', models.CharField(help_text='VAT/Tax group code', max_length=20)),
                ('tax_percentage_per_row', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax %', max_digits=5)),
                ('units_of_measurment', models.DecimalField(decimal_places=2, default=1.0, help_text='UoM conversion', max_digits=10)),
                ('uom_entry', models.IntegerField(help_text='UoM Entry ID')),
                ('measure_unit', models.CharField(help_text='Measure unit name', max_length=20)),
                ('uom_code', models.CharField(help_text='UoM Code', max_length=20)),
                ('project_code', models.CharField(blank=True, help_text='Project code', max_length=50, null=True)),
                ('u_sd', models.DecimalField(decimal_places=2, default=0.0, help_text='Special Discount %', max_digits=5)),
                ('u_ad', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional Discount %', max_digits=5)),
                ('u_exd', models.DecimalField(decimal_places=2, default=0.0, help_text='Extra Discount %', max_digits=5)),
                ('u_zerop', models.DecimalField(decimal_places=2, default=0.0, help_text='Phase Discount %', max_digits=5)),
                ('u_pl', models.IntegerField(blank=True, help_text='Policy Link', null=True)),
                ('u_bp', models.DecimalField(blank=True, decimal_places=2, help_text='Project Balance', max_digits=15, null=True)),
                ('u_policy', models.CharField(blank=True, help_text='Policy Code', max_length=50, null=True)),
                ('u_focitem', models.CharField(default='No', help_text='FOC Item (Yes/No)', max_length=10)),
                ('u_crop', models.CharField(blank=True, help_text='Crop Code', max_length=50, null=True)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_lines', to='FieldAdvisoryService.salesorder')),
            ],
            options={
                'verbose_name': 'Sales Order Line',
                'verbose_name_plural': 'Sales Order Lines',
                'ordering': ['line_num'],
            },
        ),
    ]
