# Generated by Django 5.2.4 on 2025-12-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0016_alter_salesorder_options_salesorder_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='sap_response_json',
            field=models.TextField(blank=True, help_text='Complete SAP API response', null=True),
        ),
    ]
