# Generated by Django 5.2.4 on 2025-12-09 10:48

import FieldAdvisoryService.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0018_dealerrequest_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerrequest',
            name='additional_id',
            field=models.CharField(blank=True, help_text='Additional Tax ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='card_type',
            field=models.CharField(blank=True, choices=[('cCustomer', 'Customer'), ('cSupplier', 'Supplier'), ('cLid', 'Lead')], default='cCustomer', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='country',
            field=models.CharField(blank=True, default='PK', help_text='Country Code (PK)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='debitor_account',
            field=models.CharField(blank=True, default='A020301001', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact Email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='federal_tax_id',
            field=models.CharField(blank=True, help_text='NTN Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='group_code',
            field=models.IntegerField(blank=True, default=100, help_text='Customer Group', null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='is_posted_to_sap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='mobile_phone',
            field=models.CharField(blank=True, help_text='Mobile/WhatsApp Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='posted_at',
            field=models.DateTimeField(blank=True, help_text='Posted to SAP Timestamp', null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='sap_doc_entry',
            field=models.IntegerField(blank=True, help_text='SAP Document Entry', null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='sap_error',
            field=models.TextField(blank=True, help_text='Last SAP Error Message', null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='sap_series',
            field=models.IntegerField(blank=True, default=70, help_text='BP Series Number', null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='u_leg',
            field=models.CharField(blank=True, default='17-5349', help_text='Legal Reference', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='unified_federal_tax_id',
            field=models.CharField(blank=True, help_text='Unified Tax ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='vat_group',
            field=models.CharField(blank=True, default='AT1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='vat_liable',
            field=models.CharField(blank=True, choices=[('vLiable', 'Liable'), ('vExempted', 'Exempted')], default='vLiable', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dealerrequest',
            name='whatsapp_messages',
            field=models.CharField(blank=True, default='YES', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='address',
            field=models.TextField(blank=True, help_text='Business Address', null=True),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='business_name',
            field=models.CharField(blank=True, help_text='SAP CardName', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='cnic_back',
            field=models.ImageField(blank=True, null=True, upload_to='dealer_requests/cnic_back/', validators=[FieldAdvisoryService.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='cnic_front',
            field=models.ImageField(blank=True, null=True, upload_to='dealer_requests/cnic_front/', validators=[FieldAdvisoryService.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='cnic_number',
            field=models.CharField(blank=True, help_text='Owner CNIC (13 digits)', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d{1}$', message='CNIC must be in the format 12345-1234567-1')]),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FieldAdvisoryService.company'),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Primary Phone Number', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', message='Enter a valid international phone number.')]),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='filer_status',
            field=models.CharField(blank=True, choices=[('01', 'Filer'), ('02', 'Non-Filer')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='govt_license_number',
            field=models.CharField(blank=True, help_text='U_lic', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='license_expiry',
            field=models.DateField(blank=True, help_text='U_gov', null=True),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='minimum_investment',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum should be 5 lakh', null=True),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Contact Person Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for requesting new dealer', null=True),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FieldAdvisoryService.region'),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='sap_card_code',
            field=models.CharField(blank=True, help_text='Generated BP Code from SAP', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='sap_response_json',
            field=models.TextField(blank=True, help_text='Full SAP Response', null=True),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted_to_sap', 'Posted to SAP')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FieldAdvisoryService.territory'),
        ),
        migrations.AlterField(
            model_name='dealerrequest',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FieldAdvisoryService.zone'),
        ),
    ]
