# Generated by Django 5.2.4 on 2025-12-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0019_remove_dealerrequest_sap_response_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='territory',
            options={'verbose_name': 'Territory', 'verbose_name_plural': 'Territories'},
        ),
    ]
