# Generated by Django 5.2.4 on 2025-12-19 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0020_alter_company_options_alter_territory_options_and_more'),
        ('farmers', '0010_remove_farmer_farmers_far_is_acti_2b7d8b_idx_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='dealerrequest',
        #     name='sap_response_at',
        # ),
        migrations.AddField(
            model_name='meetingschedule',
            name='feedback_from_attendees',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='fsm_name',
            field=models.CharField(default='Unknown FSM', max_length=100),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='key_topics_discussed',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='presence_of_rsm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='presence_of_zm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_schedules_region', to='FieldAdvisoryService.region'),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='suggestions_for_future',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_schedules_territory', to='FieldAdvisoryService.territory'),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='total_attendees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_schedules_zone', to='FieldAdvisoryService.zone'),
        ),
        migrations.CreateModel(
            name='MeetingScheduleAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('acreage', models.FloatField(default=0.0)),
                ('crop', models.CharField(blank=True, max_length=100)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_attendances', to='farmers.farmer')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='FieldAdvisoryService.meetingschedule')),
            ],
        ),
    ]
