# Generated by Django 5.2.4 on 2026-01-09 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0021_remove_dealerrequest_sap_response_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='dealerrequest',
        #     name='sap_response_at',
        # ),
        migrations.CreateModel(
            name='HierarchyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(help_text='Name of hierarchy level (e.g., CEO, Regional Manager)', max_length=100)),
                ('level_code', models.CharField(choices=[('ceo', 'CEO'), ('regional_manager', 'Regional Manager'), ('zone_manager', 'Zone Manager'), ('field_staff', 'Field Staff'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('level_order', models.PositiveIntegerField(help_text='Order in hierarchy (0=top, higher=bottom)')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_levels', to='FieldAdvisoryService.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hierarchy_levels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hierarchy Level',
                'verbose_name_plural': 'Hierarchy Levels',
                'ordering': ['level_order'],
                'unique_together': {('company', 'level_order')},
            },
        ),
        migrations.CreateModel(
            name='UserHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hierarchy_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hierarchies', to='FieldAdvisoryService.company')),
                ('hierarchy_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FieldAdvisoryService.hierarchylevel')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FieldAdvisoryService.region')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL)),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FieldAdvisoryService.territory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_assignment', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FieldAdvisoryService.zone')),
            ],
            options={
                'verbose_name': 'User Hierarchy',
                'verbose_name_plural': 'User Hierarchies',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
