# Generated by Django 5.2.4 on 2026-01-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0022_remove_dealerrequest_sap_response_at_hierarchylevel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerrequest',
            name='sap_response_at',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='schedule',
        ),
    ]
