# Generated by Django 5.2.4 on 2026-01-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0023_remove_schedule_from_salesorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealer',
            options={'permissions': [('manage_dealers', 'Can add/edit/delete dealers'), ('view_dealer_reports', 'Can view dealer reports'), ('approve_dealer_requests', 'Can approve dealer requests')]},
        ),
    ]
