# Generated by Django 5.2.4 on 2026-01-12 13:06

import FieldAdvisoryService.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0024_alter_dealer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='cnic_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='dealers/cnic_back/', validators=[FieldAdvisoryService.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='cnic_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='dealers/cnic_front/', validators=[FieldAdvisoryService.validators.validate_image]),
        ),
    ]
