# Generated by Django 5.2.4 on 2026-01-12 13:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0025_alter_dealer_cnic_back_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='cnic_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='dealers/cnic_back/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='cnic_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='dealers/cnic_front/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Optional staff user; defaults to current user if omitted', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
