# Generated by Django 5.2.4 on 2026-01-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0026_alter_dealer_cnic_back_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='portal_order_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique portal order ID (e.g., SO001, SA002) - Not sent to SAP', max_length=20, null=True, unique=True),
        ),
    ]
