# Generated by Django 5.2.4 on 2026-01-15 07:24

import FieldAdvisoryService.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0027_salesorder_portal_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='additional_id',
            field=models.CharField(blank=True, help_text='Additional Tax ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='business_name',
            field=models.CharField(blank=True, help_text='Business/Company Name (SAP CardName)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='card_type',
            field=models.CharField(blank=True, choices=[('cCustomer', 'Customer'), ('cSupplier', 'Supplier'), ('cLid', 'Lead')], default='cCustomer', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='country',
            field=models.CharField(blank=True, default='PK', help_text='Country Code', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='debitor_account',
            field=models.CharField(blank=True, default='A020301001', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, validators=[FieldAdvisoryService.validators.email_validator]),
        ),
        migrations.AddField(
            model_name='dealer',
            name='federal_tax_id',
            field=models.CharField(blank=True, help_text='NTN Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='filer_status',
            field=models.CharField(blank=True, choices=[('01', 'Filer'), ('02', 'Non-Filer')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='govt_license_number',
            field=models.CharField(blank=True, help_text='Government License Number (U_lic)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='group_code',
            field=models.IntegerField(blank=True, default=100, help_text='Customer Group', null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='license_expiry',
            field=models.DateField(blank=True, help_text='License Expiry Date (U_gov)', null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='minimum_investment',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum investment amount', null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='mobile_phone',
            field=models.CharField(blank=True, help_text='Mobile/WhatsApp Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='sap_series',
            field=models.IntegerField(blank=True, default=70, help_text='BP Series Number', null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='u_leg',
            field=models.CharField(blank=True, default='17-5349', help_text='Legal Reference', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='unified_federal_tax_id',
            field=models.CharField(blank=True, help_text='Unified Tax ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='vat_group',
            field=models.CharField(blank=True, default='AT1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='vat_liable',
            field=models.CharField(blank=True, choices=[('vLiable', 'Liable'), ('vExempted', 'Exempted')], default='vLiable', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='whatsapp_messages',
            field=models.CharField(blank=True, default='YES', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='contact_number',
            field=models.CharField(help_text='Primary Phone Number', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', message='Enter a valid international phone number.')]),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.CharField(help_text='Contact Person Name / Owner Name', max_length=100),
        ),
    ]
