# Generated by Django 5.2.4 on 2026-01-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0028_add_dealer_fields_from_dealer_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhierarchy',
            name='hierarchy_level',
        ),
        migrations.AlterUniqueTogether(
            name='userhierarchy',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userhierarchy',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='userhierarchy',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userhierarchy',
            name='region',
        ),
        migrations.RemoveField(
            model_name='userhierarchy',
            name='reports_to',
        ),
        migrations.RemoveField(
            model_name='userhierarchy',
            name='territory',
        ),
        migrations.RemoveField(
            model_name='userhierarchy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userhierarchy',
            name='zone',
        ),
        migrations.DeleteModel(
            name='HierarchyLevel',
        ),
        migrations.DeleteModel(
            name='UserHierarchy',
        ),
    ]
