# Generated by Django 5.2.4 on 2026-01-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0029_remove_userhierarchy_hierarchy_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-id'], 'verbose_name': 'Sales Order', 'verbose_name_plural': 'Sales Orders'},
        ),
    ]
