# Generated by Django 5.2.4 on 2026-01-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0030_alter_salesorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingschedule',
            options={'ordering': ['-id'], 'verbose_name': 'Field Advisory Meeting', 'verbose_name_plural': 'Field Advisory Meetings'},
        ),
    ]
