# Generated by Django 5.2.4 on 2026-01-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0031_alter_meetingschedule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingschedule',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
