# Generated by Django 5.2.4 on 2026-01-20 13:53

from django.db import migrations, models


def populate_meeting_ids(apps, schema_editor):
    """Populate meeting_id for existing records"""
    MeetingSchedule = apps.get_model('FieldAdvisoryService', 'MeetingSchedule')
    meetings = MeetingSchedule.objects.all().order_by('id')
    
    for index, meeting in enumerate(meetings, start=1):
        meeting.meeting_id = f'FAS{index:02d}'
        meeting.save(update_fields=['meeting_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0032_change_meetingschedule_date_to_datetime'),
    ]

    operations = [
        # First add field without unique constraint
        migrations.AddField(
            model_name='meetingschedule',
            name='meeting_id',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        # Populate existing records
        migrations.RunPython(populate_meeting_ids, migrations.RunPython.noop),
        # Then make it unique
        migrations.AlterField(
            model_name='meetingschedule',
            name='meeting_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
