# Generated by Django 5.2.4 on 2026-01-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0033_meetingschedule_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Schema name (e.g., 4B-BIO_APP, 4B-ORANG_APP). This is used for HANA database connections.', max_length=100),
        ),
    ]
