# Generated by Django 5.2.4 on 2026-02-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0034_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingschedule',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
