# Generated by Django 5.2.4 on 2026-02-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0035_alter_meetingschedule_location'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='fieldadvisoryservice_company',
        ),
        migrations.AlterModelTable(
            name='dealer',
            table='fieldadvisoryservice_dealer',
        ),
        migrations.AlterModelTable(
            name='dealerrequest',
            table='fieldadvisoryservice_dealerrequest',
        ),
        migrations.AlterModelTable(
            name='meetingschedule',
            table='fieldadvisoryservice_meetingschedule',
        ),
        migrations.AlterModelTable(
            name='meetingscheduleattendance',
            table='fieldadvisoryservice_meetingscheduleattendance',
        ),
        migrations.AlterModelTable(
            name='region',
            table='fieldadvisoryservice_region',
        ),
        migrations.AlterModelTable(
            name='salesorder',
            table='fieldadvisoryservice_salesorder',
        ),
        migrations.AlterModelTable(
            name='salesorderattachment',
            table='fieldadvisoryservice_salesorderattachment',
        ),
        migrations.AlterModelTable(
            name='salesorderline',
            table='fieldadvisoryservice_salesorderline',
        ),
        migrations.AlterModelTable(
            name='territory',
            table='fieldadvisoryservice_territory',
        ),
        migrations.AlterModelTable(
            name='zone',
            table='fieldadvisoryservice_zone',
        ),
    ]
