# Generated by Django 5.2.4 on 2026-03-13 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0037_add_phone_company_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo image', null=True, upload_to='company/logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Primary theme color in hex format (e.g., #FF5733)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_color',
            field=models.CharField(blank=True, help_text='Secondary theme color in hex format (e.g., #3498DB)', max_length=7, null=True),
        ),
    ]
