# Generated by Django 5.2.4 on 2026-04-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0040_merge_colors_into_extra_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='hana_territory_id',
            field=models.IntegerField(blank=True, help_text='SAP HANA territoryID for customer filtering. Must match OTER.territryID', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='extra_settings',
            field=models.JSONField(blank=True, default=dict, help_text='All theme/branding settings as a single JSON object. Use keys: primary_color, secondary_color, accent_color, font_family, etc.', null=True),
        ),
    ]
