# Generated by Django 5.2.4 on 2026-04-16 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0041_alter_company_extra_settings'),
        ('FieldAdvisoryService', '0041_territory_hana_territory_id_and_more'),
    ]

    operations = [
    ]
