# Generated by Django 5.2.4 on 2026-04-27 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0041_territory_hana_territory_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('product_catalog', 'Product Catalog'), ('sales_order', 'Sales Order'), ('business_partner', 'Business Partner'), ('other', 'Other')], help_text='What this series number is used for in SAP.', max_length=50)),
                ('series_number', models.IntegerField(help_text='The SAP Series integer (e.g. 77 for product catalog, 8 for sales orders).')),
                ('label', models.CharField(blank=True, help_text="Optional human-readable label (e.g. 'Agri Products Series').", max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Mark as the default series for this purpose within this company.')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_configs', to='FieldAdvisoryService.company')),
            ],
            options={
                'verbose_name': 'Company Series',
                'verbose_name_plural': 'Company Series',
                'db_table': 'fieldadvisoryservice_companyseries',
                'ordering': ['company', 'purpose', 'series_number'],
                'unique_together': {('company', 'purpose', 'series_number')},
            },
        ),
    ]
