# Generated by Django 5.2.4 on 2026-04-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0042_merge_20260416_1349'),
        ('FieldAdvisoryService', '0043_company_series_field_drop_companyseries'),
    ]

    operations = [
    ]
