# Generated by Django 5.2.4 on 2026-02-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crop',
            table='crop_management_crop',
        ),
        migrations.AlterModelTable(
            name='cropresearch',
            table='crop_management_cropresearch',
        ),
        migrations.AlterModelTable(
            name='cropvariety',
            table='crop_management_cropvariety',
        ),
        migrations.AlterModelTable(
            name='farmingpractice',
            table='crop_management_farmingpractice',
        ),
        migrations.AlterModelTable(
            name='yielddata',
            table='crop_management_yielddata',
        ),
    ]
