# Generated by Django 5.2.4 on 2026-02-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='complaint',
            table='complaints_complaint',
        ),
    ]
