# Generated by Django 5.2.4 on 2026-04-22 11:31

import django.core.validators
import django.db.models.deletion
import document_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the attachment', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the attachment', null=True)),
                ('file', models.FileField(help_text='Supported formats: PDF, DOC, DOCX, JPG, PNG', upload_to=document_management.models.attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), document_management.models.validate_file_size])),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('file_type', models.CharField(blank=True, help_text='File MIME type', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Upload timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('expired', 'Expired')], default='active', help_text='Current status of the attachment', max_length=20)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Optional expiry date for the attachment', null=True)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Whether viewing this attachment is mandatory')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for categorization', max_length=500)),
                ('created_by', models.ForeignKey(help_text='User who uploaded this attachment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'db_table': 'document_attachment',
                'ordering': ['-created_at'],
                'permissions': [('can_upload_attachment', 'Can upload attachments'), ('can_view_attachment', 'Can view attachments'), ('can_assign_attachment', 'Can assign attachments to users')],
            },
        ),
        migrations.CreateModel(
            name='AttachmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the assignment was created')),
                ('viewed', models.BooleanField(default=False, help_text='Whether the user has viewed this attachment')),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When the user first viewed the attachment', null=True)),
                ('download_count', models.IntegerField(default=0, help_text='Number of times user downloaded this attachment')),
                ('last_downloaded_at', models.DateTimeField(blank=True, help_text='Last download timestamp', null=True)),
                ('acknowledged', models.BooleanField(default=False, help_text='User acknowledgment (e.g., for policy docs)')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When user acknowledged the document', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from user or admin')),
                ('assigned_by', models.ForeignKey(help_text='Admin who made the assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments_assigned', to=settings.AUTH_USER_MODEL)),
                ('attachment', models.ForeignKey(help_text='The attachment being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='document_management.attachment')),
                ('user', models.ForeignKey(help_text='The user assigned to this attachment', on_delete=django.db.models.deletion.CASCADE, related_name='attachment_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attachment Assignment',
                'verbose_name_plural': 'Attachment Assignments',
                'db_table': 'document_attachment_assignment',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='assigned_users',
            field=models.ManyToManyField(help_text='Users who can access this attachment', related_name='assigned_attachments', through='document_management.AttachmentAssignment', through_fields=('attachment', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AttachmentDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, help_text='Download timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the download request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='document_management.attachmentassignment')),
            ],
            options={
                'verbose_name': 'Download Log',
                'verbose_name_plural': 'Download Logs',
                'db_table': 'document_attachment_download_log',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attachmentassignment',
            index=models.Index(fields=['user', '-assigned_at'], name='document_at_user_id_7fe45f_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentassignment',
            index=models.Index(fields=['attachment', 'viewed'], name='document_at_attachm_99e9d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attachmentassignment',
            unique_together={('attachment', 'user')},
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['-created_at'], name='document_at_created_df7526_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['status'], name='document_at_status_1928d8_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['created_by'], name='document_at_created_01b319_idx'),
        ),
    ]
