# Generated by Django 5.2.4 on 2025-07-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
