# Generated by Django 5.2.4 on 2025-07-21 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_alter_usersetting_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersetting',
            unique_together={('user', 'slug')},
        ),
        migrations.AddField(
            model_name='usersetting',
            name='color_theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='company_timings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ur', 'Urdu')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='value',
        ),
    ]
