# Generated by Django 5.2.4 on 2025-08-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_setting_delete_usersetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
