# Generated by Django 5.2.4 on 2026-02-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_setting_created_at_setting_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='setting',
            table='preferences_setting',
        ),
    ]
