# Generated by Django 5.2.4 on 2026-08-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_seed_additional_reports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchaccess',
            options={'verbose_name': 'Branch access', 'verbose_name_plural': 'Branch access'},
        ),
        migrations.AlterModelOptions(
            name='salesemployeeaccess',
            options={'verbose_name': 'Sales employee access', 'verbose_name_plural': 'Sales employee access'},
        ),
        migrations.AlterModelOptions(
            name='userreportaccess',
            options={'verbose_name': 'User report access', 'verbose_name_plural': 'User report access'},
        ),
    ]
