# Generated by Django 5.2.4 on 2025-07-28 10:50

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]+$', 'Only letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]+$', 'Only letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='Default', upload_to='profile_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), accounts.models.validate_image_size]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role'),
        ),
    ]
