# Generated by Django 5.2.4 on 2025-08-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_salesstaffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sales_staff',
            field=models.BooleanField(default=False),
        ),
    ]
