# Generated by Django 5.2.4 on 2025-08-15 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FieldAdvisoryService", "0006_region_name_territory_name_zone_name_and_more"),
        ("accounts", "0004_user_is_sales_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesstaffprofile",
            name="casual_leave_quota",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesstaffprofile",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="FieldAdvisoryService.company",
            ),
        ),
        migrations.AddField(
            model_name="salesstaffprofile",
            name="others_leave_quota",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesstaffprofile",
            name="sick_leave_quota",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
