# Generated by Django 5.2.4 on 2025-08-25 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FieldAdvisoryService", "0007_alter_region_company"),
        ("accounts", "0006_alter_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesstaffprofile",
            name="company",
        ),
        migrations.RemoveField(
            model_name="salesstaffprofile",
            name="region",
        ),
        migrations.RemoveField(
            model_name="salesstaffprofile",
            name="territory",
        ),
        migrations.RemoveField(
            model_name="salesstaffprofile",
            name="zone",
        ),
        migrations.AddField(
            model_name="salesstaffprofile",
            name="companies",
            field=models.ManyToManyField(
                blank=True,
                related_name="sales_profiles",
                to="FieldAdvisoryService.company",
            ),
        ),
        migrations.AddField(
            model_name="salesstaffprofile",
            name="is_vacant",
            field=models.BooleanField(
                default=False, help_text="Mark if this position is vacant"
            ),
        ),
        migrations.AddField(
            model_name="salesstaffprofile",
            name="regions",
            field=models.ManyToManyField(
                blank=True,
                related_name="sales_profiles",
                to="FieldAdvisoryService.region",
            ),
        ),
        migrations.AddField(
            model_name="salesstaffprofile",
            name="territories",
            field=models.ManyToManyField(
                blank=True,
                related_name="sales_profiles",
                to="FieldAdvisoryService.territory",
            ),
        ),
        migrations.AddField(
            model_name="salesstaffprofile",
            name="zones",
            field=models.ManyToManyField(
                blank=True,
                related_name="sales_profiles",
                to="FieldAdvisoryService.zone",
            ),
        ),
        migrations.AlterField(
            model_name="salesstaffprofile",
            name="designation",
            field=models.CharField(
                choices=[
                    ("CEO", "CEO – Orange Protection"),
                    ("NSM", "National Sales Manager"),
                    ("RSL", "Regional Sales Leader"),
                    ("DRSL", "Deputy Regional Sales Leader"),
                    ("ZM", "Zonal Manager"),
                    ("DPL", "Deputy Product Leader"),
                    ("SR_PL", "Senior Product Leader"),
                    ("PL", "Product Leader"),
                    ("SR_FSM", "Senior Farmer Service Manager"),
                    ("FSM", "Farmer Service Manager"),
                    ("SR_MTO", "Senior MTO"),
                    ("MTO", "MTO"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salesstaffprofile",
            name="employee_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="salesstaffprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
