# Generated by Django 5.2.4 on 2025-08-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_salesstaffprofile_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesstaffprofile",
            name="designation",
            field=models.CharField(
                choices=[
                    ("CEO", "CEO – Orange Protection"),
                    ("NSM", "National Sales Manager"),
                    ("RSL", "Regional Sales Leader"),
                    ("DRSL", "Deputy Regional Sales Leader"),
                    ("ZM", "Zonal Manager"),
                    ("DPL", "Deputy Product Leader"),
                    ("SR_PL", "Senior Product Leader"),
                    ("PL", "Product Leader"),
                    ("SR_FSM", "Senior Farmer Service Manager"),
                    ("FSM", "Farmer Service Manager"),
                    ("SR_MTO", "Senior MTO"),
                    ("MTO", "MTO"),
                ],
                max_length=50,
            ),
        ),
    ]
