# Generated by Django 5.2.4 on 2025-08-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FieldAdvisoryService", "0007_alter_region_company"),
        ("accounts", "0008_alter_salesstaffprofile_designation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesstaffprofile",
            name="companies",
        ),
        migrations.RemoveField(
            model_name="salesstaffprofile",
            name="regions",
        ),
        migrations.RemoveField(
            model_name="salesstaffprofile",
            name="territories",
        ),
        migrations.RemoveField(
            model_name="salesstaffprofile",
            name="zones",
        ),
        migrations.AddField(
            model_name="salesstaffprofile",
            name="company",
            field=models.ManyToManyField(
                blank=True,
                related_name="sales_profiles",
                to="FieldAdvisoryService.company",
            ),
        ),
        migrations.AddField(
            model_name="salesstaffprofile",
            name="region",
            field=models.ManyToManyField(
                blank=True,
                related_name="sales_profiles",
                to="FieldAdvisoryService.region",
            ),
        ),
        migrations.AddField(
            model_name="salesstaffprofile",
            name="territory",
            field=models.ManyToManyField(
                blank=True,
                related_name="sales_profiles",
                to="FieldAdvisoryService.territory",
            ),
        ),
        migrations.AddField(
            model_name="salesstaffprofile",
            name="zone",
            field=models.ManyToManyField(
                blank=True,
                related_name="sales_profiles",
                to="FieldAdvisoryService.zone",
            ),
        ),
    ]
