# Generated by Django 5.2.4 on 2025-08-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_old_fk"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salesstaffprofile",
            old_name="company",
            new_name="companies",
        ),
        migrations.RenameField(
            model_name="salesstaffprofile",
            old_name="region",
            new_name="regions",
        ),
        migrations.RenameField(
            model_name="salesstaffprofile",
            old_name="territory",
            new_name="territories",
        ),
        migrations.RenameField(
            model_name="salesstaffprofile",
            old_name="zone",
            new_name="zones",
        ),
    ]
