# Generated by Django 5.2.4 on 2026-01-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_dealerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DealerProfile',
        ),
    ]
