# Generated by Django 5.2.4 on 2026-01-12 10:00

from django.db import migrations
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType


def add_all_custom_permissions(apps, schema_editor):
    """Add all custom permissions defined in permissions_config.py"""
    import sys
    import os
    
    # Add parent directory to path to import permissions_config
    current_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    sys.path.insert(0, current_dir)
    
    from permissions_config import CUSTOM_PERMISSIONS
    
    permissions_created = 0
    permissions_existed = 0
    
    for app_label, models_dict in CUSTOM_PERMISSIONS.items():
        for model_name, permissions_list in models_dict.items():
            try:
                # Get the model
                Model = apps.get_model(app_label, model_name)
                content_type = ContentType.objects.get_for_model(Model)
                
                for codename, name in permissions_list:
                    permission, created = Permission.objects.get_or_create(
                        codename=codename,
                        content_type=content_type,
                        defaults={'name': name}
                    )
                    
                    if created:
                        permissions_created += 1
                        print(f"✅ Created: {app_label}.{codename} - {name}")
                    else:
                        permissions_existed += 1
                        # Update name if it changed
                        if permission.name != name:
                            permission.name = name
                            permission.save()
                            print(f"🔄 Updated: {app_label}.{codename} - {name}")
                        
            except Exception as e:
                print(f"⚠️  Error processing {app_label}.{model_name}: {e}")
    
    print(f"\n📊 Summary: {permissions_created} created, {permissions_existed} already existed")


def remove_all_custom_permissions(apps, schema_editor):
    """Remove all custom permissions"""
    from permissions_config import CUSTOM_PERMISSIONS
    
    for app_label, models_dict in CUSTOM_PERMISSIONS.items():
        for model_name, permissions_list in models_dict.items():
            try:
                Model = apps.get_model(app_label, model_name)
                content_type = ContentType.objects.get_for_model(Model)
                
                for codename, name in permissions_list:
                    Permission.objects.filter(
                        codename=codename,
                        content_type=content_type
                    ).delete()
                    
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_dealerprofile'),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(add_all_custom_permissions, remove_all_custom_permissions),
    ]
