# Generated by Django 5.2.4 on 2026-01-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_all_custom_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('manage_roles', 'Can manage roles and permissions')]},
        ),
        migrations.AlterModelOptions(
            name='salesstaffprofile',
            options={'permissions': [('manage_sales_staff', 'Can manage sales staff profiles')]},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_users', 'Can add/edit users'), ('view_user_reports', 'Can view user reports')]},
        ),
    ]
