# Generated by Django 5.2.4 on 2026-01-19 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_role_options_alter_salesstaffprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesstaffprofile',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Direct manager/supervisor of this staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='accounts.salesstaffprofile'),
        ),
    ]
