# Generated by Django 5.2.4 on 2026-01-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_salesstaffprofile_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesstaffprofile',
            options={'permissions': [('manage_sales_staff', 'Can manage sales staff profiles'), ('view_hierarchy', 'Can view reporting hierarchy'), ('manage_hierarchy', 'Can assign/change managers'), ('view_subordinate_data', 'Can view subordinates data'), ('view_all_hierarchy', 'Can view entire organization hierarchy')]},
        ),
    ]
