# Generated by Django 5.2.4 on 2026-01-19 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_hierarchy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code (e.g., CEO, RSL, FSM)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full designation name (e.g., Chief Executive Officer)', max_length=100)),
                ('level', models.IntegerField(default=0, help_text='Hierarchy level (0=highest, 10=lowest). Used for sorting.')),
                ('is_active', models.BooleanField(default=True, help_text="Inactive designations won't appear in dropdowns")),
                ('description', models.TextField(blank=True, help_text='Optional description of role responsibilities', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.AddField(
            model_name='salesstaffprofile',
            name='designation_old',
            field=models.CharField(blank=True, help_text='Temporary field for migration', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesstaffprofile',
            name='designation',
            field=models.ForeignKey(blank=True, help_text='Job title/designation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='accounts.designationmodel'),
        ),
    ]
