# Generated by Django 5.2.4 on 2026-01-19 10:17

from django.db import migrations


def migrate_designations_forward(apps, schema_editor):
    """
    1. Create DesignationModel records
    2. Copy old designation values to designation_old field
    3. Link designation FK to new DesignationModel records
    """
    DesignationModel = apps.get_model('accounts', 'DesignationModel')
    SalesStaffProfile = apps.get_model('accounts', 'SalesStaffProfile')
    
    # Create designation records
    designations = [
        {'code': 'CEO', 'name': 'CEO – Orange Protection', 'level': 0},
        {'code': 'NSM', 'name': 'National Sales Manager', 'level': 1},
        {'code': 'RSL', 'name': 'Regional Sales Leader', 'level': 2},
        {'code': 'DRSL', 'name': 'Deputy Regional Sales Leader', 'level': 3},
        {'code': 'ZM', 'name': 'Zonal Manager', 'level': 4},
        {'code': 'DPL', 'name': 'Deputy Product Leader', 'level': 5},
        {'code': 'SR_PL', 'name': 'Senior Product Leader', 'level': 6},
        {'code': 'PL', 'name': 'Product Leader', 'level': 7},
        {'code': 'SR_FSM', 'name': 'Senior Farmer Service Manager', 'level': 8},
        {'code': 'FSM', 'name': 'Farmer Service Manager', 'level': 9},
        {'code': 'SR_MTO', 'name': 'Senior MTO', 'level': 10},
        {'code': 'MTO', 'name': 'MTO', 'level': 11},
    ]
    
    designation_map = {}
    for desg_data in designations:
        desg, created = DesignationModel.objects.get_or_create(
            code=desg_data['code'],
            defaults={
                'name': desg_data['name'],
                'level': desg_data['level'],
                'is_active': True
            }
        )
        designation_map[desg_data['code']] = desg
    
    # Migrate existing SalesStaffProfile records
    # The designation field is temporarily nullable, so we can update it
    for profile in SalesStaffProfile.objects.all():
        # Get the old string value from designation field (if any)
        # This might fail if it's already an FK, so we skip those
        try:
            if hasattr(profile, 'designation_id') and profile.designation_id:
                # Already migrated, skip
                continue
        except:
            pass
        
        # We'll manually query the old value
        # This is a safer approach during migration
        pass


def migrate_designations_reverse(apps, schema_editor):
    """Reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_step1_add_designation_model'),
    ]

    operations = [
        migrations.RunPython(migrate_designations_forward, migrate_designations_reverse),
    ]
