# Generated by Django 5.2.4 on 2026-01-19 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_step2_migrate_designation_data'),
    ]

    operations = [
        # Skip RemoveField since designation_old never existed in DB
        migrations.AlterField(
            model_name='salesstaffprofile',
            name='designation',
            field=models.ForeignKey(default='', help_text='Job title/designation', on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='accounts.designationmodel'),
            preserve_default=False,
        ),
    ]
