# Generated by Django 5.2.4 on 2026-01-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_make_designation_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesstaffprofile',
            name='designation_old',
        ),
    ]
