# Generated by Django 5.2.4 on 2026-01-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_salesstaffprofile_designation_old'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_users', 'Can add/edit users'), ('view_user_reports', 'Can view user reports'), ('view_organogram', 'Can view organization hierarchy/organogram')]},
        ),
    ]
