# Generated by Django 5.2.4 on 2026-01-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_salesstaffprofile_address_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE `accounts_salesstaffprofile` MODIFY `employee_code` VARCHAR(50) NULL;",
            reverse_sql="ALTER TABLE `accounts_salesstaffprofile` MODIFY `employee_code` VARCHAR(50) NOT NULL;",
        ),
    ]
