# Generated by Django 5.2.4 on 2026-02-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20260121_1906'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='designationmodel',
            table='accounts_designationmodel',
        ),
        migrations.AlterModelTable(
            name='role',
            table='accounts_role',
        ),
        migrations.AlterModelTable(
            name='salesstaffprofile',
            table='accounts_salesstaffprofile',
        ),
        migrations.AlterModelTable(
            name='user',
            table='accounts_user',
        ),
    ]
