# Generated by Django 5.2.4 on 2026-02-20 09:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0037_add_phone_company_to_user'),
        ('accounts', '0025_fix_table_names_lowercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_users', to='FieldAdvisoryService.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for login (e.g., 03001234567, +92-300-1234567)', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[\\d\\s\\-\\+\\(\\)]+$', 'Enter a valid phone number (digits, spaces, hyphens, plus, parentheses allowed).')]),
        ),
    ]
