# Generated by Django 5.2.4 on 2026-02-26 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_add_phone_company_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('identifier', models.CharField(max_length=150)),
                ('identifier_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_password_reset_otp',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'otp', 'is_used'], name='accounts_pa_user_id_dc4e22_idx'), models.Index(fields=['identifier', 'otp'], name='accounts_pa_identif_e3d95d_idx')],
            },
        ),
    ]
