# Generated by Django 5.2.4 on 2026-03-10 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('delete', 'Delete Account'), ('deactivate', 'Deactivate Account')], default='deactivate', help_text='Type of request: delete or deactivate', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional reason provided by user', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', help_text='Current status of the request', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the request was reviewed', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin', null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deletion_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who requested account deletion/deactivation', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_deletion_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_de_user_id_d41a88_idx'), models.Index(fields=['status', 'created_at'], name='accounts_de_status_a979dd_idx')],
            },
        ),
    ]
