# Generated by Django 5.2.4 on 2026-03-10 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_accountdeletionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdeletionrequest',
            name='request_type',
            field=models.CharField(choices=[('deactivate', 'Deactivate Account')], default='deactivate', help_text='Type of request: deactivate account', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountdeletionrequest',
            name='user',
            field=models.ForeignKey(help_text='User who requested account deactivation', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
