# Generated by Django 5.2.4 on 2026-04-27 06:48

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_companies(apps, schema_editor):
    """Copy existing (sales_profile, company) pairs from the old auto M2M table."""
    SalesStaffProfile = apps.get_model('accounts', 'SalesStaffProfile')
    SalesStaffCompany = apps.get_model('accounts', 'SalesStaffCompany')

    for profile in SalesStaffProfile.objects.prefetch_related('companies').all():
        for i, company in enumerate(profile.companies.all()):
            SalesStaffCompany.objects.get_or_create(
                sales_profile=profile,
                company=company,
                defaults={
                    'employee_code': profile.employee_code if i == 0 else None,
                    'is_primary': (i == 0),
                    'is_active': True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0041_territory_hana_territory_id_and_more'),
        ('accounts', '0029_alter_accountdeletionrequest_request_type_and_more'),
    ]

    operations = [
        # Handles both cases:
        # A) Fresh server: old M2M table still exists, new table doesn't exist yet.
        # B) Dev server (partial migration): old M2M table already dropped, new table already created.

        # 1. Update state: remove old companies M2M; drop the auto table if it still exists in DB
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name='salesstaffprofile', name='companies'),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS `accounts_salesstaffprofile_companies`;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        # 2. Update state: register SalesStaffCompany model; create the table if it doesn't exist yet
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='SalesStaffCompany',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('employee_code', models.CharField(blank=True, help_text='Employee ID specific to this company (e.g. SAP employee number in that schema)', max_length=50, null=True)),
                        ('is_primary', models.BooleanField(default=False, help_text='Primary company for this user (used as default when no company context is given)')),
                        ('is_active', models.BooleanField(default=True)),
                        ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_memberships', to='FieldAdvisoryService.company')),
                        ('sales_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to='accounts.salesstaffprofile')),
                    ],
                    options={
                        'verbose_name': 'Staff Company Membership',
                        'verbose_name_plural': 'Staff Company Memberships',
                        'db_table': 'accounts_salesstaffcompany',
                        'unique_together': {('company', 'employee_code'), ('sales_profile', 'company')},
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS `accounts_salesstaffcompany` (
                            `id` bigint NOT NULL AUTO_INCREMENT,
                            `employee_code` varchar(50) NULL,
                            `is_primary` tinyint(1) NOT NULL DEFAULT 0,
                            `is_active` tinyint(1) NOT NULL DEFAULT 1,
                            `company_id` bigint NOT NULL,
                            `sales_profile_id` bigint NOT NULL,
                            PRIMARY KEY (`id`),
                            UNIQUE KEY `uq_company_employee_code` (`company_id`, `employee_code`),
                            UNIQUE KEY `uq_sales_profile_company` (`sales_profile_id`, `company_id`),
                            KEY `idx_company_id` (`company_id`),
                            KEY `idx_sales_profile_id` (`sales_profile_id`),
                            CONSTRAINT `fk_ssc_company` FOREIGN KEY (`company_id`)
                                REFERENCES `fieldadvisoryservice_company` (`id`) ON DELETE CASCADE,
                            CONSTRAINT `fk_ssc_sales_profile` FOREIGN KEY (`sales_profile_id`)
                                REFERENCES `accounts_salesstaffprofile` (`id`) ON DELETE CASCADE
                        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
                    """,
                    reverse_sql="DROP TABLE IF EXISTS `accounts_salesstaffcompany`;",
                ),
            ],
        ),
        # 3. Re-add companies M2M with through= (M2M with through never creates its own table)
        migrations.AddField(
            model_name='salesstaffprofile',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='sales_profiles', through='accounts.SalesStaffCompany', to='FieldAdvisoryService.company'),
        ),
        # 4. Data migration: populate SalesStaffCompany from existing profile employee_codes
        migrations.RunPython(migrate_existing_companies, migrations.RunPython.noop),
    ]
