# Generated by Django 5.2.4 on 2026-04-27 06:48

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_companies(apps, schema_editor):
    """Copy existing (sales_profile, company) pairs from the old auto M2M table."""
    SalesStaffProfile = apps.get_model('accounts', 'SalesStaffProfile')
    SalesStaffCompany = apps.get_model('accounts', 'SalesStaffCompany')

    for profile in SalesStaffProfile.objects.prefetch_related('companies').all():
        for i, company in enumerate(profile.companies.all()):
            SalesStaffCompany.objects.get_or_create(
                sales_profile=profile,
                company=company,
                defaults={
                    'employee_code': profile.employee_code if i == 0 else None,
                    'is_primary': (i == 0),
                    'is_active': True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0041_territory_hana_territory_id_and_more'),
        ('accounts', '0029_alter_accountdeletionrequest_request_type_and_more'),
    ]

    operations = [
        # The DB was already partially modified by a failed migration attempt:
        # - accounts_salesstaffprofile_companies (auto M2M) was already dropped
        # - accounts_salesstaffcompany was already created
        # Use SeparateDatabaseAndState to sync Django state without touching the DB.

        # 1. Update state: remove old companies M2M (auto table already gone in DB)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name='salesstaffprofile', name='companies'),
            ],
            database_operations=[],
        ),
        # 2. Update state: register SalesStaffCompany model (table already exists in DB)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='SalesStaffCompany',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('employee_code', models.CharField(blank=True, help_text='Employee ID specific to this company (e.g. SAP employee number in that schema)', max_length=50, null=True)),
                        ('is_primary', models.BooleanField(default=False, help_text='Primary company for this user (used as default when no company context is given)')),
                        ('is_active', models.BooleanField(default=True)),
                        ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_memberships', to='FieldAdvisoryService.company')),
                        ('sales_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to='accounts.salesstaffprofile')),
                    ],
                    options={
                        'verbose_name': 'Staff Company Membership',
                        'verbose_name_plural': 'Staff Company Memberships',
                        'db_table': 'accounts_salesstaffcompany',
                        'unique_together': {('company', 'employee_code'), ('sales_profile', 'company')},
                    },
                ),
            ],
            database_operations=[],
        ),
        # 3. Re-add companies M2M with through= (M2M with through never creates its own table)
        migrations.AddField(
            model_name='salesstaffprofile',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='sales_profiles', through='accounts.SalesStaffCompany', to='FieldAdvisoryService.company'),
        ),
        # 4. Data migration: populate SalesStaffCompany from existing profile employee_codes
        migrations.RunPython(migrate_existing_companies, migrations.RunPython.noop),
    ]
