# Generated by Django 5.2.4 on 2026-07-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesstaffprofile',
            name='casual_leave_quota',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='salesstaffprofile',
            name='others_leave_quota',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='salesstaffprofile',
            name='sick_leave_quota',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
