# Generated by Django 5.2.4 on 2025-08-11 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_location_attendance_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_out_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
