# Generated by Django 5.2.4 on 2025-08-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_alter_attendance_check_in_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("request", "Request")],
                default="manual",
                max_length=50,
            ),
        ),
    ]
