# Generated by Django 5.2.4 on 2025-08-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_alter_attendance_source"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestAdminModel",
        ),
    ]
