# Generated by Django 5.2.4 on 2025-08-19 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_holiday_alter_attendance_attendee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerequest",
            name="attendance",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="attendance.attendance",
            ),
            preserve_default=False,
        ),
    ]
