# Generated by Django 5.2.4 on 2025-08-19 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_alter_attendancerequest_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerequest",
            name="attendance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="attendance.attendance",
            ),
        ),
    ]
