# Generated by Django 5.2.4 on 2025-09-19 06:37

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_alter_attendancerequest_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="check_in_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="attendance_checkin/",
                validators=[attendance.models.validate_file_size],
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="attendance_checkout/",
                validators=[attendance.models.validate_file_size],
            ),
        ),
    ]
