# Generated by Django 5.2.4 on 2025-09-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_attendance_check_in_image_attendance_check_out_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="attachment",
        ),
    ]
