# Generated by Django 5.2.4 on 2025-09-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0012_attendance_check_in_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="longitude",
        ),
    ]
