# Generated by Django 5.2.4 on 2026-02-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_remove_attendance_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendance',
            table='attendance_attendance',
        ),
        migrations.AlterModelTable(
            name='attendancerequest',
            table='attendance_attendancerequest',
        ),
        migrations.AlterModelTable(
            name='holiday',
            table='attendance_holiday',
        ),
        migrations.AlterModelTable(
            name='leaverequest',
            table='attendance_leaverequest',
        ),
    ]
