# Generated by Django 5.2.4 on 2026-07-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_attendance_report_colors_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Optional. Leave blank for a full day.', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Optional. Leave blank for a full day.', null=True),
        ),
    ]
