# Generated by Django 5.2.4 on 2026-08-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_leavetype_leavequota'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='employee_code',
            field=models.CharField(blank=True, db_index=True, help_text='Employee code the location below was resolved from', max_length=50, null=True, verbose_name='Employee code'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='region',
            field=models.TextField(blank=True, help_text='Region(s) assigned to the attendee, comma separated.', null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='territory',
            field=models.TextField(blank=True, help_text='Territory/territories assigned to the attendee, comma separated.', null=True, verbose_name='Territory'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='territory_code',
            field=models.IntegerField(blank=True, db_index=True, help_text='SAP OTER.territryID, set only when the attendee has exactly one territory.', null=True, verbose_name='Territory code'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='zone',
            field=models.TextField(blank=True, help_text='Zone(s) assigned to the attendee, comma separated.', null=True, verbose_name='Zone'),
        ),
    ]
