# Generated by Django 5.2.4 on 2025-07-14 14:12

import django_google_maps.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('farm_address', django_google_maps.fields.AddressField(max_length=200)),
                ('farm_location', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
    ]
