# Generated by Django 5.2.4 on 2025-07-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='farm_address',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='farm_location',
        ),
        migrations.AddField(
            model_name='farmer',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farm_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farm_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
