# Generated by Django 5.2.4 on 2025-09-10 10:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Year")),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("kharif", "Kharif (Summer)"),
                            ("rabi", "Rabi (Winter)"),
                            ("zaid", "Zaid (Spring)"),
                        ],
                        max_length=10,
                        verbose_name="Season",
                    ),
                ),
                (
                    "crop_name",
                    models.CharField(max_length=100, verbose_name="Crop Name"),
                ),
                (
                    "area_cultivated",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Area Cultivated (acres)",
                    ),
                ),
                (
                    "total_yield",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total Yield (kg)",
                    ),
                ),
                (
                    "yield_per_acre",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Yield per Acre (kg)",
                    ),
                ),
                (
                    "input_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Input Cost",
                    ),
                ),
                (
                    "market_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Market Price per kg",
                    ),
                ),
                (
                    "total_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Total Income",
                    ),
                ),
                (
                    "profit_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Profit/Loss",
                    ),
                ),
                (
                    "farming_practices_used",
                    models.TextField(blank=True, verbose_name="Farming Practices Used"),
                ),
                (
                    "challenges_faced",
                    models.TextField(blank=True, verbose_name="Challenges Faced"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Farming History",
                "verbose_name_plural": "Farming Histories",
                "ordering": ["-year", "-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="farmer",
            options={
                "ordering": ["first_name", "last_name"],
                "verbose_name": "Farmer",
                "verbose_name_plural": "Farmers",
            },
        ),
        migrations.AddField(
            model_name="farmer",
            name="address",
            field=models.TextField(default="", verbose_name="Complete Address"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="annual_income_range",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Annual Income Range"
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="bank_account_details",
            field=models.TextField(blank=True, verbose_name="Bank Account Details"),
        ),
        migrations.AddField(
            model_name="farmer",
            name="cultivated_area",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Currently cultivated area in acres",
                max_digits=10,
                verbose_name="Cultivated Area (acres)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AddField(
            model_name="farmer",
            name="dependents_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Dependents Count"
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="district",
            field=models.CharField(default="", max_length=100, verbose_name="District"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="education_level",
            field=models.CharField(
                choices=[
                    ("none", "No Formal Education"),
                    ("primary", "Primary School"),
                    ("secondary", "Secondary School"),
                    ("higher_secondary", "Higher Secondary"),
                    ("diploma", "Diploma"),
                    ("bachelor", "Bachelor Degree"),
                    ("master", "Master Degree"),
                    ("phd", "PhD"),
                ],
                default="primary",
                max_length=20,
                verbose_name="Education Level",
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email Address"
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="family_involved_in_farming",
            field=models.BooleanField(
                default=False, verbose_name="Family Involved in Farming"
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="family_members_count",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Family Members Count"
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="farm_ownership_type",
            field=models.CharField(
                choices=[
                    ("owned", "Owned"),
                    ("leased", "Leased"),
                    ("shared", "Shared/Partnership"),
                    ("tenant", "Tenant Farming"),
                ],
                default="",
                max_length=20,
                verbose_name="Farm Ownership Type",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="farmer_id",
            field=models.CharField(
                default="", max_length=20, unique=True, verbose_name="Farmer ID"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="farming_experience",
            field=models.CharField(
                choices=[
                    ("beginner", "0-2 years"),
                    ("intermediate", "3-10 years"),
                    ("experienced", "11-20 years"),
                    ("expert", "20+ years"),
                ],
                default="",
                max_length=20,
                verbose_name="Farming Experience",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="farming_methods",
            field=models.TextField(
                blank=True,
                help_text="Traditional, modern, organic, etc.",
                verbose_name="Farming Methods",
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="father_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Father Name"
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="first_name",
            field=models.CharField(
                default="", max_length=50, verbose_name="First Name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="",
                max_length=10,
                verbose_name="Gender",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="irrigation_source",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Irrigation Source"
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AddField(
            model_name="farmer",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Is Verified"),
        ),
        migrations.AddField(
            model_name="farmer",
            name="land_documents",
            field=models.TextField(
                blank=True,
                help_text="Details about land ownership documents",
                verbose_name="Land Documents",
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="last_name",
            field=models.CharField(default="", max_length=50, verbose_name="Last Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
        ),
        migrations.AddField(
            model_name="farmer",
            name="main_crops_grown",
            field=models.TextField(
                default="",
                help_text="List of main crops grown by the farmer",
                verbose_name="Main Crops Grown",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="National ID/CNIC",
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Additional Notes"),
        ),
        migrations.AddField(
            model_name="farmer",
            name="occupation_besides_farming",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Other Occupation"
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Postal Code"
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="primary_phone",
            field=models.CharField(
                default="",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Primary Phone",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="farmer_profiles/",
                verbose_name="Profile Picture",
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="province",
            field=models.CharField(
                default="", max_length=100, verbose_name="Province/State"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="registered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registered_farmers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registered By",
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="registration_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Registration Date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="secondary_phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Secondary Phone",
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="tehsil",
            field=models.CharField(default="", max_length=100, verbose_name="Tehsil"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="total_land_area",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total land area in acres",
                max_digits=10,
                verbose_name="Total Land Area (acres)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="village",
            field=models.CharField(default="", max_length=100, verbose_name="Village"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="years_of_farming",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Years of Farming"
            ),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="current_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Current Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="current_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Current Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="farm_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Farm Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="farm_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Farm Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Full Name"),
        ),
        migrations.AddIndex(
            model_name="farmer",
            index=models.Index(
                fields=["farmer_id"], name="farmers_far_farmer__f0df00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmer",
            index=models.Index(
                fields=["district", "tehsil"], name="farmers_far_distric_df7bac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmer",
            index=models.Index(
                fields=["registration_date"], name="farmers_far_registr_694913_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmer",
            index=models.Index(
                fields=["is_active", "is_verified"],
                name="farmers_far_is_acti_2b7d8b_idx",
            ),
        ),
        migrations.AddField(
            model_name="farminghistory",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farming_history",
                to="farmers.farmer",
                verbose_name="Farmer",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="farminghistory",
            unique_together={("farmer", "year", "season", "crop_name")},
        ),
    ]
