# Generated by Django 5.2.4 on 2025-09-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0002_farminghistory_alter_farmer_options_farmer_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="cultivated_area",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Currently cultivated area in acres",
                max_digits=10,
                verbose_name="Cultivated Area (acres)",
            ),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="total_land_area",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total land area in acres",
                max_digits=10,
                verbose_name="Total Land Area (acres)",
            ),
        ),
    ]
