# Generated by Django 5.2.4 on 2025-09-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0003_alter_farmer_cultivated_area_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE farmers_farminghistory 
            ADD COLUMN farmer_id BIGINT NULL;
            """,
            reverse_sql="""
            ALTER TABLE farmers_farminghistory 
            DROP COLUMN farmer_id;
            """
        ),
        migrations.RunSQL(
            """
            DELETE FROM farmers_farminghistory WHERE id IS NOT NULL;
            """,
            reverse_sql="""
            -- No reverse operation needed for data deletion
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE farmers_farminghistory 
            MODIFY COLUMN farmer_id BIGINT NOT NULL;
            """,
            reverse_sql="""
            ALTER TABLE farmers_farminghistory 
            MODIFY COLUMN farmer_id BIGINT NULL;
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE farmers_farminghistory 
            ADD CONSTRAINT farmers_farminghistory_farmer_id_fk 
            FOREIGN KEY (farmer_id) REFERENCES farmers_farmer(id) 
            ON DELETE CASCADE;
            """,
            reverse_sql="""
            ALTER TABLE farmers_farminghistory 
            DROP FOREIGN KEY farmers_farminghistory_farmer_id_fk;
            """
        ),
        migrations.RunSQL(
            """
            CREATE INDEX farmers_farminghistory_farmer_id_idx 
            ON farmers_farminghistory(farmer_id);
            """,
            reverse_sql="""
            DROP INDEX farmers_farminghistory_farmer_id_idx 
            ON farmers_farminghistory;
            """
        ),
    ]
