# Generated by Django 5.2.4 on 2025-09-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0004_auto_20250915_0938"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmer",
            name="annual_income_range",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="bank_account_details",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="cultivated_area",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="current_latitude",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="current_longitude",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="dependents_count",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="family_involved_in_farming",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="family_members_count",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="farm_latitude",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="farm_longitude",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="farm_ownership_type",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="farming_experience",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="farming_methods",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="irrigation_source",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="land_documents",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="main_crops_grown",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="occupation_besides_farming",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="years_of_farming",
        ),
    ]
