# Generated by Django 5.2.4 on 2025-09-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0005_remove_farmer_annual_income_range_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmer",
            name="national_id",
        ),
        migrations.AddField(
            model_name="farmer",
            name="cnic",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="CNIC"
            ),
        ),
    ]
