# Generated by Django 5.2.4 on 2025-09-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0006_remove_farmer_national_id_farmer_cnic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmer",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="is_verified",
        ),
    ]
