# Generated by Django 5.2.4 on 2025-09-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0007_remove_farmer_farmers_far_is_acti_2b7d8b_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="farmer_id",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Farmer ID"
            ),
        ),
    ]
