# Generated by Django 5.2.4 on 2025-09-24 13:16

from django.db import migrations


def update_farmer_ids(apps, schema_editor):
    """Update all farmer IDs to new FM01, FM02 format"""
    Farmer = apps.get_model('farmers', 'Farmer')
    
    # Get all farmers ordered by ID to maintain consistency
    farmers = Farmer.objects.all().order_by('id')
    
    for index, farmer in enumerate(farmers, start=1):
        new_farmer_id = f"FM{index:02d}"
        farmer.farmer_id = new_farmer_id
        farmer.save()


def reverse_update_farmer_ids(apps, schema_editor):
    """Reverse operation - not implemented as it would lose original IDs"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0008_remove_farmer_farmers_far_is_acti_2b7d8b_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(update_farmer_ids, reverse_update_farmer_ids),
    ]
