# Generated by Django 5.2.4 on 2025-09-24 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0009_auto_20250924_1816"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="farmer",
            name="farmers_far_is_acti_2b7d8b_idx",
        ),
        migrations.AlterField(
            model_name="farminghistory",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_records",
                to="farmers.farmer",
                verbose_name="Farmer",
            ),
        ),
    ]
