# Generated by Django 5.2.4 on 2026-01-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0010_remove_farmer_farmers_far_is_acti_2b7d8b_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmer',
            options={'ordering': ['-id'], 'verbose_name': 'Farmer', 'verbose_name_plural': 'Farmers'},
        ),
    ]
