# Generated by Django 5.2.4 on 2026-02-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0012_farmer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='crop_calendar',
            field=models.TextField(blank=True, help_text='Planned crop calendar and rotation schedule', null=True, verbose_name='Crop Calendar'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='current_crops_and_acreage',
            field=models.TextField(blank=True, help_text='Details of current crops sown with acreage information', null=True, verbose_name='Total Current Crops Sown and Acreage'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='address',
            field=models.TextField(blank=True, verbose_name='Complete Address'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Province/State'),
        ),
    ]
