# Generated by Django 5.2.4 on 2026-02-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0013_farmer_crop_calendar_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='farmer',
            table='farmers_farmer',
        ),
        migrations.AlterModelTable(
            name='farminghistory',
            table='farmers_farminghistory',
        ),
    ]
