# Generated by Django 5.2.4 on 2026-03-02 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0014_fix_table_names_lowercase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Associated user account for login', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='farmer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='farminghistory',
            table=None,
        ),
    ]
