# Generated by Django 5.2.4 on 2026-07-15 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0015_alter_farmer_user_alter_farmer_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Primary Phone'),
        ),
    ]
