# Generated by Django 5.2.4 on 2025-07-15 13:51

import django.db.models.deletion
import farmerMeetingDataEntry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('fsm_name', models.CharField(default='Unknown FSM', max_length=100)),
                ('territory', models.CharField(default='Unknown Territory', max_length=100)),
                ('zone', models.CharField(default='Unknown Zone', max_length=100)),
                ('region', models.CharField(default='Unknown Region', max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(default='Not specified', max_length=200)),
                ('total_attendees', models.PositiveIntegerField(default=0)),
                ('key_topics_discussed', models.TextField(default='Not specified')),
                ('presence_of_zm_rsm', models.BooleanField(default=False)),
                ('feedback_from_attendees', models.TextField(blank=True, null=True)),
                ('suggestions_for_future', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('acreage', models.FloatField(default=0.0)),
                ('crop', models.CharField(max_length=100)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='farmerMeetingDataEntry.meeting')),
            ],
            options={
                'db_table': 'farmer_meeting_attendees',
            },
        ),
        migrations.CreateModel(
            name='MeetingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=farmerMeetingDataEntry.models.upload_to_meeting, validators=[farmerMeetingDataEntry.models.validate_file_size, farmerMeetingDataEntry.models.validate_file_extension])),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='farmerMeetingDataEntry.meeting')),
            ],
        ),
    ]
