# Generated by Django 5.2.4 on 2025-08-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmerMeetingDataEntry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
