# Generated by Django 5.2.4 on 2025-09-03 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FieldAdvisoryService", "0007_alter_region_company"),
        ("farmerMeetingDataEntry", "0003_fieldday_fielddayattendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="region_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meetings_region",
                to="FieldAdvisoryService.region",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="territory_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meetings_territory",
                to="FieldAdvisoryService.territory",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="zone_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meetings_zone",
                to="FieldAdvisoryService.zone",
            ),
        ),
    ]
