# Generated by Django 5.2.4 on 2025-09-03 12:29

import django.core.validators
import farmerMeetingDataEntry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmerMeetingDataEntry",
            "0004_meeting_region_fk_meeting_territory_fk_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingattachment",
            name="file",
            field=models.FileField(
                upload_to=farmerMeetingDataEntry.models.upload_to_meeting,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "png",
                            "jpg",
                            "jpeg",
                            "pdf",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                        ]
                    ),
                    farmerMeetingDataEntry.models.validate_file_size,
                ],
            ),
        ),
    ]
