# Generated by Django 5.2.4 on 2025-09-08 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FieldAdvisoryService", "0013_dealer_card_code"),
        ("farmerMeetingDataEntry", "0005_alter_meetingattachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldday",
            name="region_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="field_days_region",
                to="FieldAdvisoryService.region",
            ),
        ),
        migrations.AddField(
            model_name="fieldday",
            name="territory_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="field_days_territory",
                to="FieldAdvisoryService.territory",
            ),
        ),
        migrations.AddField(
            model_name="fieldday",
            name="zone_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="field_days_zone",
                to="FieldAdvisoryService.zone",
            ),
        ),
    ]
