# Generated by Django 5.2.4 on 2025-09-12 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FieldAdvisoryService", "0013_dealer_card_code"),
        (
            "farmerMeetingDataEntry",
            "0006_fieldday_region_fk_fieldday_territory_fk_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fieldday",
            name="region",
        ),
        migrations.RemoveField(
            model_name="fieldday",
            name="territory",
        ),
        migrations.RemoveField(
            model_name="fieldday",
            name="zone",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="region",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="territory",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="zone",
        ),
        migrations.AddField(
            model_name="fieldday",
            name="company_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="field_days_company",
                to="FieldAdvisoryService.company",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="company_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meetings_company",
                to="FieldAdvisoryService.company",
            ),
        ),
    ]
