# Generated by Django 5.2.4 on 2025-09-29 10:45

import django.core.validators
import django.db.models.deletion
import farmerMeetingDataEntry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmerMeetingDataEntry",
            "0007_remove_fieldday_region_remove_fieldday_territory_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldday",
            name="title",
            field=models.CharField(
                help_text="Enter the name of the Field Service Manager (FSM)",
                max_length=200,
                verbose_name="Name of FSM",
            ),
        ),
        migrations.CreateModel(
            name="FieldDayAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=farmerMeetingDataEntry.models.upload_to_field_day,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "png",
                                    "jpg",
                                    "jpeg",
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                ]
                            ),
                            farmerMeetingDataEntry.models.validate_file_size,
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="farmerMeetingDataEntry.fieldday",
                    ),
                ),
            ],
        ),
    ]
