# Generated by Django 5.2.4 on 2025-09-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmerMeetingDataEntry", "0008_alter_fieldday_title_fielddayattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldday",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
