# Generated by Django 5.2.4 on 2025-09-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmerMeetingDataEntry", "0009_alter_fieldday_date_alter_meeting_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fieldday",
            old_name="remarks",
            new_name="feedback",
        ),
        migrations.RemoveField(
            model_name="fieldday",
            name="objectives",
        ),
        migrations.AddField(
            model_name="fieldday",
            name="demonstrations_conducted",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of demonstrations conducted"
            ),
        ),
    ]
