# Generated by Django 5.2.4 on 2025-09-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmerMeetingDataEntry", "0010_rename_fieldday_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fieldday",
            name="status",
        ),
    ]
