# Generated by Django 5.2.4 on 2025-09-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmerMeetingDataEntry", "0011_remove_fieldday_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meeting",
            old_name="presence_of_zm_rsm",
            new_name="presence_of_zm",
        ),
        migrations.AddField(
            model_name="meeting",
            name="presence_of_rsm",
            field=models.BooleanField(default=False),
        ),
    ]
