# Generated by Django 5.2.4 on 2025-09-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmerMeetingDataEntry",
            "0012_rename_presence_of_zm_rsm_meeting_presence_of_zm_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldday",
            name="total_participants",
            field=models.PositiveIntegerField(
                default=0, help_text="Total number of participants in the field day"
            ),
        ),
    ]
