# Generated by Django 5.2.4 on 2025-10-01 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmerMeetingDataEntry", "0013_fieldday_total_participants"),
        ("farmers", "0010_remove_farmer_farmers_far_is_acti_2b7d8b_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fielddayattendance",
            name="farmer",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to farmer record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field_day_attendances",
                to="farmers.farmer",
            ),
        ),
        migrations.AlterField(
            model_name="fielddayattendance",
            name="acreage",
            field=models.FloatField(
                default=0.0, help_text="Acreage for this specific field day"
            ),
        ),
        migrations.AlterField(
            model_name="fielddayattendance",
            name="contact_number",
            field=models.CharField(
                blank=True,
                help_text="Contact number (auto-filled from farmer record if linked)",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="fielddayattendance",
            name="crop",
            field=models.CharField(
                blank=True, help_text="Crop discussed/demonstrated", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="fielddayattendance",
            name="farmer_name",
            field=models.CharField(
                blank=True,
                help_text="Farmer name (auto-filled from farmer record if linked)",
                max_length=100,
            ),
        ),
    ]
