# Generated by Django 5.2.4 on 2025-10-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmerMeetingDataEntry", "0014_fielddayattendance_farmer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fielddayattendance",
            name="attendee_note",
            field=models.CharField(
                blank=True,
                help_text="Additional notes about attendee discrepancies or information",
                max_length=200,
                null=True,
            ),
        ),
    ]
