# Generated by Django 5.2.4 on 2025-10-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmerMeetingDataEntry", "0015_add_attendee_note_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fielddayattendance",
            name="attendee_note",
        ),
    ]
