# Generated by Django 5.2.4 on 2025-10-02 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmerMeetingDataEntry", "0016_remove_attendee_note_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fielddayattendance",
            name="crop",
            field=models.CharField(
                blank=True,
                help_text="Crop discussed/demonstrated (deprecated - use crops relationship)",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="FieldDayAttendanceCrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crop_name",
                    models.CharField(help_text="Name of the crop", max_length=100),
                ),
                (
                    "acreage",
                    models.FloatField(
                        default=0.0, help_text="Acreage for this specific crop"
                    ),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crops",
                        to="farmerMeetingDataEntry.fielddayattendance",
                    ),
                ),
            ],
            options={
                "db_table": "field_day_attendance_crops",
                "unique_together": {("attendance", "crop_name")},
            },
        ),
    ]
