# Generated by Django 5.2.4 on 2025-10-07 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmerMeetingDataEntry",
            "0017_alter_fielddayattendance_crop_fielddayattendancecrop",
        ),
        ("farmers", "0010_remove_farmer_farmers_far_is_acti_2b7d8b_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmerattendance",
            name="farmer",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to farmer record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting_attendances",
                to="farmers.farmer",
            ),
        ),
        migrations.AlterField(
            model_name="farmerattendance",
            name="contact_number",
            field=models.CharField(
                blank=True,
                help_text="Contact number (auto-filled from farmer record if linked)",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="farmerattendance",
            name="farmer_name",
            field=models.CharField(
                blank=True,
                help_text="Farmer name (auto-filled from farmer record if linked)",
                max_length=100,
            ),
        ),
    ]
