# Generated by Django 5.2.4 on 2026-01-09 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerMeetingDataEntry', '0018_farmerattendance_farmer_and_more'),
        ('farmers', '0010_remove_farmer_farmers_far_is_acti_2b7d8b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddayattendance',
            name='acreage',
            field=models.FloatField(default=0.0, help_text='Acreage for this specific field day', verbose_name='Acreage'),
        ),
        migrations.AlterField(
            model_name='fielddayattendance',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact number (auto-filled from farmer record if linked)', max_length=15, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='fielddayattendance',
            name='crop',
            field=models.CharField(blank=True, help_text='Crop discussed/demonstrated (deprecated - use crops relationship)', max_length=100, verbose_name='Crop'),
        ),
        migrations.AlterField(
            model_name='fielddayattendance',
            name='farmer',
            field=models.ForeignKey(blank=True, help_text='Link to farmer record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_day_attendances', to='farmers.farmer', verbose_name='Farmer'),
        ),
        migrations.AlterField(
            model_name='fielddayattendance',
            name='farmer_name',
            field=models.CharField(blank=True, help_text='Farmer name (auto-filled from farmer record if linked)', max_length=100, verbose_name='Farmer Name'),
        ),
    ]
