# Generated by Django 5.2.4 on 2026-01-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerMeetingDataEntry', '0019_alter_fielddayattendance_acreage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldday',
            options={'ordering': ['-id'], 'verbose_name': 'Field Day', 'verbose_name_plural': 'Field Days'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-id'], 'verbose_name': 'Farmer Advisory Meeting', 'verbose_name_plural': 'Farmer Advisory Meetings'},
        ),
    ]
