# Generated by Django 5.2.4 on 2026-02-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerMeetingDataEntry', '0020_alter_fieldday_options_alter_meeting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='products_discussed',
            field=models.TextField(blank=True, help_text='Products discussed during the meeting', null=True),
        ),
        migrations.AlterField(
            model_name='fieldday',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, default='Not specified', max_length=200),
        ),
    ]
