# Generated by Django 5.2.4 on 2026-02-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerMeetingDataEntry', '0021_meeting_products_discussed_alter_fieldday_location_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fieldday',
            table='farmermeetingdataentry_fieldday',
        ),
        migrations.AlterModelTable(
            name='fielddayattachment',
            table='farmermeetingdataentry_fielddayattachment',
        ),
        migrations.AlterModelTable(
            name='fielddayattendance',
            table='farmermeetingdataentry_fielddayattendance',
        ),
        migrations.AlterModelTable(
            name='meeting',
            table='farmermeetingdataentry_meeting',
        ),
    ]
