# Generated by Django 5.2.4 on 2026-02-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerMeetingDataEntry', '0022_fix_table_names_lowercase'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meetingattachment',
            table='farmermeetingdataentry_meetingattachment',
        ),
    ]
