# Generated by Django 5.2.4 on 2026-07-30 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldAdvisoryService', '0044_merge_20260428_1710'),
        ('farmerMeetingDataEntry', '0023_fix_meetingattachment_table_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HPMRequisition',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('requisition_date', models.DateField(help_text="Date the requisition was raised (the form's 'Requisition Date').")),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_date', models.DateField()),
                ('meeting_location', models.CharField(max_length=200)),
                ('expected_attendees', models.PositiveIntegerField(default=0, help_text='No. of farmers / attendees expected.')),
                ('purpose', models.TextField(help_text='Purpose of meeting (product related campaign & sale commitment).')),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('ceo_remarks', models.TextField(blank=True, help_text="Approver's remarks; carries the reason on rejection.")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hpm_requisitions_company', to='FieldAdvisoryService.company')),
                ('region_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hpm_requisitions_region', to='FieldAdvisoryService.region')),
                ('responsible_person', models.ForeignKey(blank=True, help_text='Staff member accountable for arranging the meeting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hpm_responsible_for', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Who approved or rejected it (prints as CEO signature).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hpm_requisitions_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Manager who raised this requisition (prints as GM/BM Name).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hpm_requisitions', to=settings.AUTH_USER_MODEL)),
                ('territory_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hpm_requisitions_territory', to='FieldAdvisoryService.territory')),
                ('zone_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hpm_requisitions_zone', to='FieldAdvisoryService.zone')),
            ],
            options={
                'verbose_name': 'HPM Requisition',
                'verbose_name_plural': 'HPM Requisitions',
                'db_table': 'farmermeetingdataentry_hpmrequisition',
                'ordering': ['-id'],
                'permissions': [('approve_hpmrequisition', 'Can approve or reject HPM requisitions')],
                'indexes': [models.Index(fields=['status', 'requisition_date'], name='farmermeeti_status_bca8fc_idx'), models.Index(fields=['submitted_by', 'status'], name='farmermeeti_submitt_e5dc0b_idx')],
            },
        ),
    ]
