# Generated by Django 5.2.4 on 2026-07-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerMeetingDataEntry', '0024_hpmrequisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpmrequisition',
            name='meeting_date',
            field=models.DateTimeField(help_text='Date and start time of the meeting.'),
        ),
    ]
