# Generated by Django 5.2.4 on 2026-07-31 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerMeetingDataEntry', '0026_add_created_at_to_meeting_and_fieldday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hpmrequisition',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('approve_hpmrequisition', 'Can approve or reject HPM requisitions')], 'verbose_name': 'HPM Requisition', 'verbose_name_plural': 'HPM Requisitions'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Farmer Meeting', 'verbose_name_plural': 'Farmer Meetings'},
        ),
    ]
