# Generated by Django 5.2.4 on 2026-07-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerMeetingDataEntry', '0027_alter_hpmrequisition_options_alter_meeting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Field Advisory', 'verbose_name_plural': 'Field Advisory'},
        ),
    ]
