# Generated by Django 5.2.4 on 2026-08-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerMeetingDataEntry', '0028_alter_meeting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='sap_employee_code',
            field=models.CharField(blank=True, db_index=True, help_text='SAP employee code the location below was resolved from', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='sap_region',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='sap_territory',
            field=models.CharField(blank=True, db_index=True, help_text='Blank when the employee covers several SAP territories', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='sap_territory_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='SAP OTER.territryID, set only when SAP pinned down exactly one territory', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='sap_zone',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
