# Generated by Django 5.2.4 on 2026-08-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerMeetingDataEntry', '0029_meeting_sap_employee_code_meeting_sap_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='sap_territories',
            field=models.TextField(blank=True, help_text="Every SAP territory assigned to the employee, comma separated. Always recorded, so a multi-territory FSM's coverage is not lost when no single territory applies to the meeting.", null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='sap_territory',
            field=models.CharField(blank=True, db_index=True, help_text='The one territory this meeting is filed against. Auto-set when the employee covers exactly one; otherwise set by posting sap_territory_id.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='sap_territory_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='SAP OTER.territryID of sap_territory', null=True),
        ),
    ]
