# Generated by Django 5.2.4 on 2026-08-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerMeetingDataEntry', '0030_meeting_sap_territories_alter_meeting_sap_territory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='sap_territories',
        ),
    ]
