# Generated by Django 5.2.4 on 2026-08-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerMeetingDataEntry', '0031_remove_meeting_sap_territories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='sap_region',
            field=models.TextField(blank=True, help_text='Region(s) SAP assigns the employee, comma separated.', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='sap_territory',
            field=models.TextField(blank=True, help_text='Territory/territories SAP assigns the employee, comma separated. Narrows to the single one when the meeting names it via sap_territory_id.', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='sap_territory_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='SAP OTER.territryID - set only when one territory applies, either because the employee has just one or because the meeting named it.', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='sap_zone',
            field=models.TextField(blank=True, help_text='Zone(s) SAP assigns the employee, comma separated.', null=True),
        ),
    ]
