# Generated by Django 5.2.4 on 2026-08-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerMeetingDataEntry', '0033_rename_sap_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldday',
            name='employee_code',
            field=models.CharField(blank=True, db_index=True, help_text='Employee code the location below was resolved from', max_length=50, null=True, verbose_name='Employee code'),
        ),
        migrations.AddField(
            model_name='fieldday',
            name='region',
            field=models.TextField(blank=True, help_text='Region(s) assigned to the employee, comma separated.', null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='fieldday',
            name='territory',
            field=models.TextField(blank=True, help_text='Territory/territories assigned to the employee, comma separated. Narrows to the single one when the record names it via territory_code.', null=True, verbose_name='Territory'),
        ),
        migrations.AddField(
            model_name='fieldday',
            name='territory_code',
            field=models.IntegerField(blank=True, db_index=True, help_text='SAP OTER.territryID - set only when one territory applies, either because the employee has just one or because the record named it.', null=True, verbose_name='Territory code'),
        ),
        migrations.AddField(
            model_name='fieldday',
            name='zone',
            field=models.TextField(blank=True, help_text='Zone(s) assigned to the employee, comma separated.', null=True, verbose_name='Zone'),
        ),
        migrations.AddField(
            model_name='hpmrequisition',
            name='employee_code',
            field=models.CharField(blank=True, db_index=True, help_text='Employee code the location below was resolved from', max_length=50, null=True, verbose_name='Employee code'),
        ),
        migrations.AddField(
            model_name='hpmrequisition',
            name='region',
            field=models.TextField(blank=True, help_text='Region(s) assigned to the employee, comma separated.', null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='hpmrequisition',
            name='territory',
            field=models.TextField(blank=True, help_text='Territory/territories assigned to the employee, comma separated. Narrows to the single one when the record names it via territory_code.', null=True, verbose_name='Territory'),
        ),
        migrations.AddField(
            model_name='hpmrequisition',
            name='territory_code',
            field=models.IntegerField(blank=True, db_index=True, help_text='SAP OTER.territryID - set only when one territory applies, either because the employee has just one or because the record named it.', null=True, verbose_name='Territory code'),
        ),
        migrations.AddField(
            model_name='hpmrequisition',
            name='zone',
            field=models.TextField(blank=True, help_text='Zone(s) assigned to the employee, comma separated.', null=True, verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='territory',
            field=models.TextField(blank=True, help_text='Territory/territories assigned to the employee, comma separated. Narrows to the single one when the record names it via territory_code.', null=True, verbose_name='Territory'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='territory_code',
            field=models.IntegerField(blank=True, db_index=True, help_text='SAP OTER.territryID - set only when one territory applies, either because the employee has just one or because the record named it.', null=True, verbose_name='Territory code'),
        ),
    ]
