# Generated by Django 5.2.4 on 2025-09-23 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("variety", models.CharField(blank=True, max_length=100, null=True)),
                ("season", models.CharField(blank=True, max_length=50, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CropStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage_name", models.CharField(max_length=200)),
                ("days_after_sowing", models.IntegerField()),
                ("brand", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "active_ingredient",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "dose_per_acre",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("purpose", models.TextField(blank=True, null=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="crop_manage.crop",
                    ),
                ),
            ],
        ),
    ]
