# Generated by Django 5.2.4 on 2025-11-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_manage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station", models.CharField(max_length=100)),
                ("trial_name", models.CharField(max_length=100)),
                ("location_area", models.CharField(max_length=200)),
                ("crop_variety", models.CharField(max_length=200)),
                ("application_date", models.DateField()),
                ("design_replicates", models.CharField(max_length=100)),
                ("water_volume_used", models.CharField(max_length=50)),
                (
                    "previous_sprays",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("temp_min_c", models.DecimalField(decimal_places=1, max_digits=4)),
                ("temp_max_c", models.DecimalField(decimal_places=1, max_digits=4)),
                ("humidity_min_percent", models.PositiveIntegerField()),
                ("humidity_max_percent", models.PositiveIntegerField()),
                (
                    "wind_velocity_kmh",
                    models.DecimalField(decimal_places=1, max_digits=4),
                ),
                ("rainfall", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Trial",
                "verbose_name_plural": "Trials",
                "ordering": ["station", "trial_name"],
            },
        ),
    ]
