# Generated by Django 5.2.4 on 2025-11-10 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_manage", "0002_trial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g., T1, T2, Treatment 1", max_length=20
                    ),
                ),
                ("crop_stage_soil", models.TextField(blank=True, null=True)),
                ("pest_stage_start", models.TextField(blank=True, null=True)),
                (
                    "crop_safety_stress_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Type of insect/weeds/disease and % control",
                        null=True,
                    ),
                ),
                ("growth_improvement_type", models.TextField(blank=True, null=True)),
                ("best_dose", models.CharField(blank=True, max_length=100, null=True)),
                ("others", models.TextField(blank=True, null=True)),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="crop_manage.trial",
                    ),
                ),
            ],
            options={
                "ordering": ["trial", "label"],
            },
        ),
        migrations.CreateModel(
            name="TrialImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="trial_images/")),
                (
                    "image_type",
                    models.CharField(
                        choices=[("before", "Before"), ("after", "After")],
                        max_length=10,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200, null=True)),
                ("taken_at", models.DateField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="crop_manage.trialtreatment",
                    ),
                ),
            ],
            options={
                "ordering": ["treatment", "image_type", "uploaded_at"],
            },
        ),
    ]
