# Generated by Django 5.2.4 on 2025-11-10 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_manage", "0003_trialtreatment_trialimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("brand", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "active_ingredient",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "formulation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["name", "brand"],
            },
        ),
        migrations.AddField(
            model_name="trialtreatment",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="treatments",
                to="crop_manage.product",
            ),
        ),
    ]
