# Generated by Django 5.2.4 on 2025-11-10 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_manage", "0004_product_trialtreatment_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="cropstage",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CropStageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="crop_stage_images/")),
                ("caption", models.CharField(blank=True, max_length=200, null=True)),
                ("taken_at", models.DateField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="crop_manage.cropstage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop Stage Image",
                "verbose_name_plural": "Crop Stage Images",
                "ordering": ["crop_stage", "uploaded_at"],
            },
        ),
    ]
