# Generated by Django 5.2.4 on 2025-11-10 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_manage", "0005_cropstage_remarks_cropstageimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationGuideline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("herbicide", "Herbicide"),
                            ("insecticide", "Insecticide"),
                            ("fungicide", "Fungicide"),
                            ("micronutrient", "Micronutrient"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "type_label",
                    models.CharField(
                        help_text="e.g., Pre-emergence, Chewing, Preventive, Seed Coating",
                        max_length=100,
                    ),
                ),
                (
                    "pest_life_stages",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "time_of_application",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "water_volume",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("nozzles", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "number_of_applications",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "observation_time",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "method_of_application",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "method_of_observation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "trial_starting_stage",
                    models.CharField(
                        blank=True,
                        help_text="Crop or pest stage at trial start",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_guidelines",
                        to="crop_manage.crop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Guideline",
                "verbose_name_plural": "Application Guidelines",
                "ordering": ["crop", "category", "type_label"],
            },
        ),
    ]
