# Generated by Django 5.2.4 on 2025-11-10 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_manage", "0006_applicationguideline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("weed", "Weed"),
                            ("insect", "Insect"),
                            ("disease", "Disease"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "species_group",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "life_stages",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Egg, Larva, Nymph, Adult",
                        max_length=120,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="PestManagementGuideline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "control_category",
                    models.CharField(
                        choices=[
                            ("herbicide", "Herbicide"),
                            ("insecticide", "Insecticide"),
                            ("fungicide", "Fungicide"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "type_label",
                    models.CharField(
                        help_text="e.g., Pre-emergence, Chewing, Preventive, Seed Treatment",
                        max_length=100,
                    ),
                ),
                (
                    "time_of_application",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "water_volume",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("nozzles", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "number_of_applications",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "observation_time",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "method_of_application",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "method_of_observation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "trial_starting_stage",
                    models.CharField(
                        blank=True,
                        help_text="Crop or pest stage at trial start",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pest_guidelines",
                        to="crop_manage.crop",
                    ),
                ),
                (
                    "pest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guidelines",
                        to="crop_manage.pest",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pest_guidelines",
                        to="crop_manage.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pest Management Guideline",
                "verbose_name_plural": "Pest Management Guidelines",
                "ordering": ["pest", "crop", "control_category", "type_label"],
            },
        ),
        migrations.DeleteModel(
            name="ApplicationGuideline",
        ),
    ]
