# Generated by Django 5.2.4 on 2025-11-10 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_manage", "0007_pest_pestmanagementguideline_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComparativePerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observation_day", models.IntegerField()),
                ("efficacy_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "reference_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons",
                        to="crop_manage.product",
                    ),
                ),
                (
                    "trial_treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons",
                        to="crop_manage.trialtreatment",
                    ),
                ),
            ],
            options={
                "ordering": ["trial_treatment", "reference_product", "observation_day"],
            },
        ),
        migrations.CreateModel(
            name="DoseResponseObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dose_ml_per_acre",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("observation_day", models.IntegerField()),
                ("efficacy_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "trial_treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dose_response",
                        to="crop_manage.trialtreatment",
                    ),
                ),
            ],
            options={
                "ordering": ["trial_treatment", "dose_ml_per_acre", "observation_day"],
            },
        ),
        migrations.CreateModel(
            name="EnvironmentalCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "humidity_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "wind_speed_kmh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "soil_moisture_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "rainfall_24h_mm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "trial_treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environmental_conditions",
                        to="crop_manage.trialtreatment",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommended_dose_ml_per_acre",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "basis",
                    models.TextField(
                        help_text="Evidence and rationale for recommendation"
                    ),
                ),
                (
                    "success_metrics",
                    models.TextField(
                        blank=True,
                        help_text="Criteria used to judge efficacy and success",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="crop_manage.crop",
                    ),
                ),
                (
                    "pest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="crop_manage.pest",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="crop_manage.product",
                    ),
                ),
                (
                    "source_trial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_recommendations",
                        to="crop_manage.trial",
                    ),
                ),
            ],
            options={
                "ordering": ["crop", "pest", "product"],
            },
        ),
        migrations.CreateModel(
            name="SpeciesPerformanceObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation_day",
                    models.IntegerField(help_text="Days after application"),
                ),
                (
                    "control_efficacy_pct",
                    models.DecimalField(
                        decimal_places=2, help_text="0–100%", max_digits=5
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Visual Assessment, Counting per sq.m",
                        max_length=60,
                        null=True,
                    ),
                ),
                (
                    "dose_ml_per_acre",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "pest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_observations",
                        to="crop_manage.pest",
                    ),
                ),
                (
                    "trial_treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_observations",
                        to="crop_manage.trialtreatment",
                    ),
                ),
            ],
            options={
                "ordering": ["trial_treatment", "pest", "observation_day"],
            },
        ),
        migrations.CreateModel(
            name="TrialInitCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crop_health_ok",
                    models.BooleanField(
                        default=True,
                        help_text="Crop must be healthy with no stress symptoms",
                    ),
                ),
                (
                    "weed_growth_stage",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 3–5 leaf stage for weeds",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "meets_requirements",
                    models.BooleanField(
                        default=False,
                        help_text="Whether baseline meets initiation criteria",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "trial",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="init_condition",
                        to="crop_manage.trial",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrialRepetitionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dose_min_ml_per_acre",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "dose_max_ml_per_acre",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "adjustment_increment_ml_per_acre",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "success_metrics",
                    models.TextField(
                        help_text="How success is defined (e.g., >85% control at DAA-21)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="planned",
                        help_text="planned/scheduled/completed",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repetition_plans",
                        to="crop_manage.crop",
                    ),
                ),
                (
                    "pest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repetition_plans",
                        to="crop_manage.pest",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repetition_plans",
                        to="crop_manage.product",
                    ),
                ),
            ],
            options={
                "ordering": ["crop", "pest", "product"],
            },
        ),
    ]
