# Generated by Django 5.2.4 on 2025-11-10 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_manage", "0008_comparativeperformance_doseresponseobservation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comparativeperformance",
            name="efficacy_pct",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Observed efficacy (%) of the reference product",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="comparativeperformance",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Comparison notes or anomalies", null=True
            ),
        ),
        migrations.AlterField(
            model_name="comparativeperformance",
            name="observation_day",
            field=models.IntegerField(help_text="Days after application"),
        ),
        migrations.AlterField(
            model_name="comparativeperformance",
            name="reference_product",
            field=models.ForeignKey(
                help_text="Comparator/reference product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparisons",
                to="crop_manage.product",
            ),
        ),
        migrations.AlterField(
            model_name="comparativeperformance",
            name="trial_treatment",
            field=models.ForeignKey(
                help_text="Treatment row being compared",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparisons",
                to="crop_manage.trialtreatment",
            ),
        ),
        migrations.AlterField(
            model_name="doseresponseobservation",
            name="dose_ml_per_acre",
            field=models.DecimalField(
                decimal_places=2, help_text="Dose evaluated (ml per acre)", max_digits=7
            ),
        ),
        migrations.AlterField(
            model_name="doseresponseobservation",
            name="efficacy_pct",
            field=models.DecimalField(
                decimal_places=2, help_text="Observed efficacy (%)", max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="doseresponseobservation",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Notes about response or variability", null=True
            ),
        ),
        migrations.AlterField(
            model_name="doseresponseobservation",
            name="observation_day",
            field=models.IntegerField(help_text="Days after application"),
        ),
        migrations.AlterField(
            model_name="doseresponseobservation",
            name="trial_treatment",
            field=models.ForeignKey(
                help_text="Treatment this dose-response record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dose_response",
                to="crop_manage.trialtreatment",
            ),
        ),
        migrations.AlterField(
            model_name="environmentalcondition",
            name="humidity_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Relative humidity (%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="environmentalcondition",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional weather details or context", null=True
            ),
        ),
        migrations.AlterField(
            model_name="environmentalcondition",
            name="rainfall_24h_mm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Rainfall in last 24 hours (mm)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="environmentalcondition",
            name="recorded_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Auto-recorded timestamp when conditions were captured",
            ),
        ),
        migrations.AlterField(
            model_name="environmentalcondition",
            name="soil_moisture_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Soil moisture (%) or relative scale",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="environmentalcondition",
            name="temperature_c",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ambient temperature (°C) at application/observation",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="environmentalcondition",
            name="trial_treatment",
            field=models.ForeignKey(
                help_text="Treatment row this environment snapshot belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environmental_conditions",
                to="crop_manage.trialtreatment",
            ),
        ),
        migrations.AlterField(
            model_name="environmentalcondition",
            name="wind_speed_kmh",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Wind speed (km/h) measured at canopy height",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pest",
            name="category",
            field=models.CharField(
                choices=[
                    ("weed", "Weed"),
                    ("insect", "Insect"),
                    ("disease", "Disease"),
                ],
                help_text="Select whether this is a weed, insect, or disease",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pest",
            name="name",
            field=models.CharField(
                help_text="Common name of pest/species or pathogen",
                max_length=120,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="pest",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Identification cues, local names, or any remarks",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pest",
            name="species_group",
            field=models.CharField(
                blank=True,
                help_text="Optional group/genus (e.g., Echinochloa spp., Aphididae)",
                max_length=120,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pestmanagementguideline",
            name="control_category",
            field=models.CharField(
                choices=[
                    ("herbicide", "Herbicide"),
                    ("insecticide", "Insecticide"),
                    ("fungicide", "Fungicide"),
                ],
                help_text="Type of control: Herbicide, Insecticide, or Fungicide",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pestmanagementguideline",
            name="crop",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: limit guideline to a specific crop",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pest_guidelines",
                to="crop_manage.crop",
            ),
        ),
        migrations.AlterField(
            model_name="pestmanagementguideline",
            name="method_of_application",
            field=models.CharField(
                blank=True,
                help_text="Application method (e.g., foliar spray, seed treatment, drench)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pestmanagementguideline",
            name="method_of_observation",
            field=models.CharField(
                blank=True,
                help_text="Observation method (e.g., visual scale, counts per m²)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pestmanagementguideline",
            name="nozzles",
            field=models.CharField(
                blank=True,
                help_text="Recommended nozzle type/model",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pestmanagementguideline",
            name="number_of_applications",
            field=models.CharField(
                blank=True,
                help_text="Total sprays and intervals (e.g., 2–3 sprays, 10-day interval)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pestmanagementguideline",
            name="observation_time",
            field=models.CharField(
                blank=True,
                help_text="When efficacy should be observed/measured",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pestmanagementguideline",
            name="pest",
            field=models.ForeignKey(
                help_text="Select the target pest for this guideline",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guidelines",
                to="crop_manage.pest",
            ),
        ),
        migrations.AlterField(
            model_name="pestmanagementguideline",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Products applicable under this guideline",
                related_name="pest_guidelines",
                to="crop_manage.product",
            ),
        ),
        migrations.AlterField(
            model_name="pestmanagementguideline",
            name="time_of_application",
            field=models.CharField(
                blank=True,
                help_text="When to apply relative to crop/pest stage",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pestmanagementguideline",
            name="water_volume",
            field=models.CharField(
                blank=True,
                help_text="Spray volume (e.g., L/acre or L/ha)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="crop",
            field=models.ForeignKey(
                help_text="Target crop for recommendation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="crop_manage.crop",
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="pest",
            field=models.ForeignKey(
                help_text="Target pest for recommendation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="crop_manage.pest",
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="product",
            field=models.ForeignKey(
                help_text="Recommended product based on trial observations",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="crop_manage.product",
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="recommended_dose_ml_per_acre",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Recommended dose (ml per acre)",
                max_digits=7,
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="source_trial",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: link to the trial that supports this recommendation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_recommendations",
                to="crop_manage.trial",
            ),
        ),
        migrations.AlterField(
            model_name="speciesperformanceobservation",
            name="dose_ml_per_acre",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Dose used for this observation (ml per acre)",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="speciesperformanceobservation",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Extra context: plot conditions, anomalies, etc.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="speciesperformanceobservation",
            name="pest",
            field=models.ForeignKey(
                help_text="Observed target species/pest",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="species_observations",
                to="crop_manage.pest",
            ),
        ),
        migrations.AlterField(
            model_name="speciesperformanceobservation",
            name="trial_treatment",
            field=models.ForeignKey(
                help_text="Treatment under which the observation is recorded",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="species_observations",
                to="crop_manage.trialtreatment",
            ),
        ),
        migrations.AlterField(
            model_name="trialinitcondition",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Any remarks about baseline setup and observations",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="trialinitcondition",
            name="trial",
            field=models.OneToOneField(
                help_text="Linked trial; one baseline record per trial",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="init_condition",
                to="crop_manage.trial",
            ),
        ),
        migrations.AlterField(
            model_name="trialrepetitionplan",
            name="adjustment_increment_ml_per_acre",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Step size to adjust dose between repetitions (ml per acre)",
                max_digits=7,
            ),
        ),
        migrations.AlterField(
            model_name="trialrepetitionplan",
            name="crop",
            field=models.ForeignKey(
                help_text="Crop planned for repeated trials",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repetition_plans",
                to="crop_manage.crop",
            ),
        ),
        migrations.AlterField(
            model_name="trialrepetitionplan",
            name="dose_max_ml_per_acre",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Maximum planned dose (ml per acre)",
                max_digits=7,
            ),
        ),
        migrations.AlterField(
            model_name="trialrepetitionplan",
            name="dose_min_ml_per_acre",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Minimum planned dose (ml per acre)",
                max_digits=7,
            ),
        ),
        migrations.AlterField(
            model_name="trialrepetitionplan",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional plan notes or considerations",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="trialrepetitionplan",
            name="pest",
            field=models.ForeignKey(
                help_text="Target pest for repeated trials",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repetition_plans",
                to="crop_manage.pest",
            ),
        ),
        migrations.AlterField(
            model_name="trialrepetitionplan",
            name="product",
            field=models.ForeignKey(
                help_text="Product to be evaluated in repetitions",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repetition_plans",
                to="crop_manage.product",
            ),
        ),
        migrations.AlterField(
            model_name="trialrepetitionplan",
            name="status",
            field=models.CharField(
                default="planned",
                help_text="Trial repetition status: planned/scheduled/completed",
                max_length=30,
            ),
        ),
    ]
