# Generated by Django 5.2.4 on 2025-11-10 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_manage", "0009_alter_comparativeperformance_efficacy_pct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="name",
            field=models.CharField(
                help_text="Crop common name (e.g., Wheat, Rice)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="remarks",
            field=models.TextField(
                blank=True, help_text="Any additional notes about the crop", null=True
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="season",
            field=models.CharField(
                blank=True,
                help_text="Growing season (e.g., Rabi/Kharif)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="variety",
            field=models.CharField(
                blank=True,
                help_text="Optional variety/hybrid (e.g., HD-2967)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cropstage",
            name="active_ingredient",
            field=models.CharField(
                blank=True,
                help_text="Active ingredient(s) used (e.g., Thiram + Carboxin)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cropstage",
            name="brand",
            field=models.CharField(
                blank=True,
                help_text="Brand/manufacturer of product used at this stage",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cropstage",
            name="crop",
            field=models.ForeignKey(
                help_text="Select the crop this stage belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="crop_manage.crop",
            ),
        ),
        migrations.AlterField(
            model_name="cropstage",
            name="days_after_sowing",
            field=models.IntegerField(
                help_text="Number of days from sowing to this stage"
            ),
        ),
        migrations.AlterField(
            model_name="cropstage",
            name="dose_per_acre",
            field=models.CharField(
                blank=True,
                help_text="Dose per acre (units included, e.g., 2.5 gm/kg seed)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cropstage",
            name="purpose",
            field=models.TextField(
                blank=True,
                help_text="Purpose or objective of this stage/treatment",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cropstage",
            name="remarks",
            field=models.TextField(
                blank=True, help_text="Additional notes or instructions", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cropstage",
            name="stage_name",
            field=models.CharField(
                help_text="Stage title (e.g., Pre-sowing, Tillering)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="active_ingredient",
            field=models.CharField(
                blank=True,
                help_text="Active ingredient(s) and concentration",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(
                blank=True,
                help_text="Company/brand (e.g., UPL, Bayer)",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="formulation",
            field=models.CharField(
                blank=True,
                help_text="Formulation type (e.g., EC, SC, WG)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(help_text="Commercial product name", max_length=150),
        ),
        migrations.AlterField(
            model_name="product",
            name="remarks",
            field=models.TextField(
                blank=True,
                help_text="Extra information, label guidance, or local notes",
                null=True,
            ),
        ),
    ]
