# Generated by Django 5.2.4 on 2025-11-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_manage', '0010_alter_crop_name_alter_crop_remarks_alter_crop_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestmanagementguideline',
            name='control_category',
            field=models.CharField(choices=[('herbicide', 'Herbicide'), ('fungicide', 'Fungicide'), ('insecticide', 'Insecticide'), ('micronutrient', 'Micronutrient')], help_text='Type of control: Herbicide, Fungicide, Insecticide, or Micronutrient', max_length=20),
        ),
    ]
