# Generated by Django 5.2.4 on 2025-12-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop_manage', '0011_alter_pestmanagementguideline_control_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comparativeperformance',
            options={'ordering': ['trial_treatment', 'reference_product', 'observation_day'], 'verbose_name': 'Comparative Performance', 'verbose_name_plural': 'Comparative Performance Records'},
        ),
        migrations.AlterModelOptions(
            name='crop',
            options={'verbose_name': 'Crop', 'verbose_name_plural': 'Crops'},
        ),
        migrations.AlterModelOptions(
            name='cropstage',
            options={'verbose_name': 'Crop Stage', 'verbose_name_plural': 'Crop Stages'},
        ),
        migrations.AlterModelOptions(
            name='doseresponseobservation',
            options={'ordering': ['trial_treatment', 'dose_ml_per_acre', 'observation_day'], 'verbose_name': 'Dose Response Observation', 'verbose_name_plural': 'Dose Response Observations'},
        ),
        migrations.AlterModelOptions(
            name='environmentalcondition',
            options={'ordering': ['-recorded_at'], 'verbose_name': 'Environmental Condition', 'verbose_name_plural': 'Environmental Conditions'},
        ),
        migrations.AlterModelOptions(
            name='pest',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Pest', 'verbose_name_plural': 'Pests'},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['crop', 'pest', 'product'], 'verbose_name': 'Recommendation', 'verbose_name_plural': 'Recommendations'},
        ),
        migrations.AlterModelOptions(
            name='speciesperformanceobservation',
            options={'ordering': ['trial_treatment', 'pest', 'observation_day'], 'verbose_name': 'Species Performance Observation', 'verbose_name_plural': 'Species Performance Observations'},
        ),
        migrations.AlterModelOptions(
            name='trialimage',
            options={'ordering': ['treatment', 'image_type', 'uploaded_at'], 'verbose_name': 'Trial Image', 'verbose_name_plural': 'Trial Images'},
        ),
        migrations.AlterModelOptions(
            name='trialinitcondition',
            options={'verbose_name': 'Trial Initial Condition', 'verbose_name_plural': 'Trial Initial Conditions'},
        ),
        migrations.AlterModelOptions(
            name='trialrepetitionplan',
            options={'ordering': ['crop', 'pest', 'product'], 'verbose_name': 'Trial Repetition Plan', 'verbose_name_plural': 'Trial Repetition Plans'},
        ),
        migrations.AlterModelOptions(
            name='trialtreatment',
            options={'ordering': ['trial', 'label'], 'verbose_name': 'Trial Treatment', 'verbose_name_plural': 'Trial Treatments'},
        ),
    ]
