# Generated by Django 5.2.4 on 2026-02-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop_manage', '0012_alter_comparativeperformance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comparativeperformance',
            table='crop_manage_comparativeperformance',
        ),
        migrations.AlterModelTable(
            name='crop',
            table='crop_manage_crop',
        ),
        migrations.AlterModelTable(
            name='cropstage',
            table='crop_manage_cropstage',
        ),
        migrations.AlterModelTable(
            name='cropstageimage',
            table='crop_manage_cropstageimage',
        ),
        migrations.AlterModelTable(
            name='doseresponseobservation',
            table='crop_manage_doseresponseobservation',
        ),
        migrations.AlterModelTable(
            name='environmentalcondition',
            table='crop_manage_environmentalcondition',
        ),
        migrations.AlterModelTable(
            name='pest',
            table='crop_manage_pest',
        ),
        migrations.AlterModelTable(
            name='pestmanagementguideline',
            table='crop_manage_pestmanagementguideline',
        ),
        migrations.AlterModelTable(
            name='product',
            table='crop_manage_product',
        ),
        migrations.AlterModelTable(
            name='recommendation',
            table='crop_manage_recommendation',
        ),
        migrations.AlterModelTable(
            name='speciesperformanceobservation',
            table='crop_manage_speciesperformanceobservation',
        ),
        migrations.AlterModelTable(
            name='trial',
            table='crop_manage_trial',
        ),
        migrations.AlterModelTable(
            name='trialimage',
            table='crop_manage_trialimage',
        ),
        migrations.AlterModelTable(
            name='trialinitcondition',
            table='crop_manage_trialinitcondition',
        ),
        migrations.AlterModelTable(
            name='trialrepetitionplan',
            table='crop_manage_trialrepetitionplan',
        ),
        migrations.AlterModelTable(
            name='trialtreatment',
            table='crop_manage_trialtreatment',
        ),
    ]
