# Generated by Django 5.2.4 on 2026-07-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='auth_outcome',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
