# Generated by Django 5.2.4 on 2026-07-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_activitylog_auth_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='attempted_identifier',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='is_suspicious',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
