# Generated by Django 5.2.4 on 2026-07-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_activitylog_attempted_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='error_detail',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='query_string',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
