# Generated by Django 5.2.4 on 2026-06-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0007_ledgersettings_footer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgersettings',
            name='company_name',
            field=models.CharField(blank=True, default='FOUR BROTHERS BIOLOGIC AG PAKISTAN', help_text='Displayed below the group name in the PDF header (bold, larger font). Leave blank to use the company name resolved from SAP.', max_length=300, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='font_size_company_name',
            field=models.PositiveSmallIntegerField(default=13, help_text='Font size (pt) for the company name in the PDF header (e.g. 13).', verbose_name='Font Size — Company Name'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='font_size_dates',
            field=models.PositiveSmallIntegerField(default=9, help_text='Font size (pt) for the From/To date range line (e.g. 9).', verbose_name='Font Size — Date Range'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='font_size_group_name',
            field=models.PositiveSmallIntegerField(default=11, help_text='Font size (pt) for the group name in the PDF header (e.g. 11).', verbose_name='Font Size — Group Name'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='font_size_report_title',
            field=models.PositiveSmallIntegerField(default=10, help_text='Font size (pt) for the report title line (e.g. 10).', verbose_name='Font Size — Report Title'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='font_size_table_data',
            field=models.PositiveSmallIntegerField(default=8, help_text='Font size (pt) for table data rows (e.g. 8).', verbose_name='Font Size — Table Data Rows'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='font_size_table_header',
            field=models.PositiveSmallIntegerField(default=8, help_text='Font size (pt) for the table column-header row (e.g. 8).', verbose_name='Font Size — Table Header Row'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='group_name',
            field=models.CharField(default='Four Brothers Group', help_text='Displayed as the top-left bold heading in the PDF header.', max_length=200, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='smart_stamp_image',
            field=models.ImageField(blank=True, help_text='Circular stamp shown at top-right of the PDF. Recommended size: 150×150 px PNG with transparent background.', null=True, upload_to='ledger_settings/', verbose_name='Smart Agriculture Stamp Image'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='table_header_bg_color',
            field=models.CharField(default='#ffffff', help_text='Hex color for the column-header row background (e.g. #ffffff for white).', max_length=20, verbose_name='Table Header Background Color'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='table_header_text_color',
            field=models.CharField(default='#000000', help_text='Hex color for the column-header text (e.g. #000000 for black).', max_length=20, verbose_name='Table Header Text Color'),
        ),
    ]
