# Generated by Django 5.2.4 on 2025-11-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HanaConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'HANA Connect',
                'verbose_name_plural': 'HANA Connect',
                'managed': False,
            },
        ),
    ]
