# Generated by Django 5.2.4 on 2025-12-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap_integration', '0002_hanaconnect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Policy', 'verbose_name_plural': 'Policies'},
        ),
    ]
