# Generated by Django 5.2.4 on 2026-01-12 09:57

from django.db import migrations
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType


def add_hana_connect_permission(apps, schema_editor):
    """Add permission for HANA Connect access"""
    try:
        HanaConnect = apps.get_model('sap_integration', 'HanaConnect')
        content_type = ContentType.objects.get_for_model(HanaConnect)
        
        # Create the permission if it doesn't exist
        permission, created = Permission.objects.get_or_create(
            codename='access_hana_connect',
            content_type=content_type,
            defaults={'name': 'Can access HANA Connect'}
        )
        
        if created:
            print(f"✅ Created permission: {permission}")
        else:
            print(f"ℹ️ Permission already exists: {permission}")
    except Exception as e:
        print(f"⚠️ Error creating permission: {e}")


def remove_hana_connect_permission(apps, schema_editor):
    """Remove the HANA Connect permission"""
    try:
        Permission.objects.filter(codename='access_hana_connect').delete()
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('sap_integration', '0003_alter_policy_options'),
    ]

    operations = [
        migrations.RunPython(add_hana_connect_permission, remove_hana_connect_permission),
    ]
