# Generated by Django 5.2.4 on 2026-01-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap_integration', '0004_add_hana_connect_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hanaconnect',
            options={'managed': False, 'permissions': [('access_hana_connect', 'Can access HANA Connect dashboard'), ('view_policy_balance', 'Can view policy balance reports'), ('view_customer_data', 'Can view customer data'), ('view_item_master', 'Can view item master list'), ('view_sales_reports', 'Can view sales vs achievement reports'), ('sync_policies', 'Can sync policies from SAP'), ('post_to_sap', 'Can post data to SAP')], 'verbose_name': 'HANA Connect', 'verbose_name_plural': 'HANA Connect'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-updated_at'], 'permissions': [('manage_policies', 'Can manage policy records')], 'verbose_name': 'Policy', 'verbose_name_plural': 'Policies'},
        ),
    ]
