# Generated by Django 5.2.4 on 2026-01-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap_integration', '0005_alter_hanaconnect_options_alter_policy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hanaconnect',
            options={'managed': False, 'permissions': [('access_hana_connect', 'Can access HANA Connect dashboard'), ('post_to_sap', 'Can post data to SAP'), ('sync_policies', 'Can sync policies from SAP'), ('view_sales_vs_achievement_geo', 'Can view Sales VS Achievement (Geo Inv)'), ('view_sales_vs_achievement_territory', 'Can view Sales VS Achievement (Territory)'), ('view_sales_vs_achievement_profit', 'Can view Sales VS Achievement (Profit)'), ('view_products_catalog', 'Can view Products Catalog'), ('view_policy_balance', 'Can view Policy Wise Customer Balance'), ('view_policy_link', 'Can view and link policies'), ('view_all_territories', 'Can view All Territories'), ('view_cwl', 'Can view CWL (Customer Watch List)'), ('view_sales_orders', 'Can view Sales Orders'), ('create_sales_orders', 'Can create Sales Orders'), ('edit_sales_orders', 'Can edit Sales Orders'), ('view_customer_list', 'Can view Customer List (LOV)'), ('view_item_master', 'Can view Item Master List'), ('view_project_list', 'Can view Project List'), ('view_crop_master', 'Can view Crop Master List'), ('view_tax_codes', 'Can view Sales Tax Codes'), ('view_customer_address', 'Can view Customer Address'), ('view_contact_person', 'Can view Contact Person Name'), ('view_child_customers', 'Can view Child Customers'), ('view_warehouse_for_item', 'Can view Warehouse for Item')], 'verbose_name': 'HANA Connect', 'verbose_name_plural': 'HANA Connect'},
        ),
    ]
