# Generated by Django 5.2.4 on 2026-01-15 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_integration', '0006_add_detailed_hana_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_entry', models.CharField(help_text='DocEntry from SAP @ODID table', max_length=50)),
                ('item_code', models.CharField(help_text='U_ItemCode - Disease identification code', max_length=100, unique=True)),
                ('item_name', models.CharField(help_text='U_ItemName - Disease name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='U_Description - Detailed disease description', null=True)),
                ('disease_name', models.CharField(help_text='U_Disease - Disease scientific/common name', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Is this disease entry active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disease Identification',
                'verbose_name_plural': 'Disease Identifications',
                'ordering': ['disease_name', 'item_code'],
                'permissions': [('view_disease_identification', 'Can view disease identifications'), ('manage_disease_identification', 'Can manage disease identifications')],
            },
        ),
        migrations.CreateModel(
            name='RecommendedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_item_code', models.CharField(help_text='SAP Item Code of the recommended product (e.g., FG00259)', max_length=100)),
                ('product_name', models.CharField(help_text='Product name', max_length=255)),
                ('dosage', models.CharField(blank=True, help_text="Recommended dosage (e.g., '500ml per acre')", max_length=255, null=True)),
                ('application_method', models.TextField(blank=True, help_text='How to apply the product', null=True)),
                ('timing', models.CharField(blank=True, help_text="When to apply (e.g., 'Early morning', 'At first symptoms')", max_length=255, null=True)),
                ('precautions', models.TextField(blank=True, help_text='Safety precautions and warnings', null=True)),
                ('priority', models.IntegerField(default=1, help_text='Recommendation priority (1=highest)')),
                ('effectiveness_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Effectiveness rating out of 10', max_digits=3, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this recommendation active?')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this recommendation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(help_text='Disease for which this product is recommended', on_delete=django.db.models.deletion.CASCADE, related_name='recommended_products', to='sap_integration.diseaseidentification')),
            ],
            options={
                'verbose_name': 'Recommended Product',
                'verbose_name_plural': 'Recommended Products',
                'ordering': ['disease', 'priority', '-effectiveness_rating'],
                'permissions': [('view_recommended_product', 'Can view recommended products'), ('manage_recommended_product', 'Can manage recommended products')],
                'unique_together': {('disease', 'product_item_code')},
            },
        ),
    ]
