# Generated by Django 5.2.4 on 2026-02-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap_integration', '0007_diseaseidentification_recommendedproduct'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diseaseidentification',
            table='sap_integration_diseaseidentification',
        ),
        migrations.AlterModelTable(
            name='hanaconnect',
            table='sap_integration_hanaconnect',
        ),
        migrations.AlterModelTable(
            name='policy',
            table='sap_integration_policy',
        ),
        migrations.AlterModelTable(
            name='recommendedproduct',
            table='sap_integration_recommendedproduct',
        ),
    ]
