# Generated by Django 5.2.4 on 2026-01-19 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User who owns this cart', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'permissions': [('add_to_cart', 'Can add products to cart'), ('manage_cart', 'Can manage shopping cart')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Unique order number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Current order status', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', help_text='Payment status', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total order amount', max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid so far', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Order notes or special instructions', null=True)),
                ('shipping_address', models.TextField(blank=True, help_text='Shipping address', null=True)),
                ('sap_order_id', models.CharField(blank=True, help_text='SAP Sales Order ID if synced', max_length=100, null=True)),
                ('is_synced_to_sap', models.BooleanField(default=False, help_text='Has this order been synced to SAP?')),
                ('sap_sync_date', models.DateTimeField(blank=True, help_text='When was this order synced to SAP?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When was this order completed/delivered?', null=True)),
                ('user', models.ForeignKey(help_text='User who placed this order', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
                'permissions': [('view_order_history', 'Can view order history'), ('manage_orders', 'Can manage orders'), ('sync_orders_to_sap', 'Can sync orders to SAP')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_item_code', models.CharField(help_text='SAP Item Code of the product', max_length=100)),
                ('product_name', models.CharField(help_text='Product name at time of order', max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity ordered')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at time of order', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal (quantity × unit_price)', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Item-specific notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(help_text='Order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_item_code', models.CharField(help_text='SAP Item Code of the product (e.g., FG00259)', max_length=100)),
                ('product_name', models.CharField(help_text='Product name for display', max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of this product')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Unit price at the time of adding to cart', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Special instructions or notes', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this item still active in cart?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this item was added to cart')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(help_text='Cart this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'ordering': ['-created_at'],
                'unique_together': {('cart', 'product_item_code', 'is_active')},
            },
        ),
    ]
