# Generated by Django 5.2.4 on 2026-01-23 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Unique transaction identifier', max_length=100, unique=True)),
                ('payment_method', models.CharField(choices=[('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery')], help_text='Payment method used', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Payment status', max_length=20)),
                ('jazzcash_transaction_id', models.CharField(blank=True, help_text='JazzCash transaction reference number', max_length=100, null=True)),
                ('jazzcash_response_code', models.CharField(blank=True, help_text='JazzCash response code', max_length=10, null=True)),
                ('jazzcash_response_message', models.TextField(blank=True, help_text='JazzCash response message', null=True)),
                ('jazzcash_payment_token', models.CharField(blank=True, help_text='JazzCash payment token for verification', max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, help_text='Customer phone number used for payment', max_length=20, null=True)),
                ('customer_email', models.EmailField(blank=True, help_text='Customer email for payment confirmation', max_length=254, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional payment notes', null=True)),
                ('raw_response', models.JSONField(blank=True, help_text='Raw payment gateway response for debugging', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When payment was initiated')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('order', models.ForeignKey(help_text='Order this payment is for', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cart.order')),
                ('user', models.ForeignKey(help_text='User who made the payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'permissions': [('view_payment_history', 'Can view payment history'), ('process_payments', 'Can process payments'), ('refund_payments', 'Can refund payments')],
            },
        ),
    ]
