# Generated by Django 5.2.4 on 2026-02-16 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_date'], 'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_date'], 'permissions': [('view_order_history', 'Can view order history'), ('manage_orders', 'Can manage orders'), ('sync_orders_to_sap', 'Can sync orders to SAP')], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_date'], 'permissions': [('view_payment_history', 'Can view payment history'), ('process_payments', 'Can process payments'), ('refund_payments', 'Can refund payments')], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='updated_at',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='updated_at',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_at',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='updated_at',
            new_name='updated_date',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, help_text="Customer's email address", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_first_name',
            field=models.CharField(blank=True, help_text="Customer's first name", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_last_name',
            field=models.CharField(blank=True, help_text="Customer's last name", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, help_text="Customer's phone number", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Cash on Delivery'), ('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa'), ('credit_card', 'Credit Card (Visa/Mastercard)')], help_text='Selected payment method', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_phone',
            field=models.CharField(blank=True, help_text='Phone number for mobile wallet payments (JazzCash/Easypaisa)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_area',
            field=models.CharField(blank=True, help_text='Area/Locality', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, help_text='Postal Code / ZIP Code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, help_text='Shipping address (street address)', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('inprogress', 'In Progress'), ('delivered', 'Delivered')], default='pending', help_text='Current order status', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('inprogress', 'In Progress'), ('delivered', 'Delivered')], help_text='Previous status', max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('inprogress', 'In Progress'), ('delivered', 'Delivered')], help_text='New status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for this status change', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who changed the status', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Order this status change belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='cart.order')),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
