# Generated by Django 5.2.4 on 2026-02-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart_cart',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_cartitem',
        ),
        migrations.AlterModelTable(
            name='order',
            table='cart_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='cart_orderitem',
        ),
        migrations.AlterModelTable(
            name='orderstatushistory',
            table='cart_orderstatushistory',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='cart_payment',
        ),
    ]
