# Generated by Django 5.2.4 on 2026-03-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_fix_table_names_lowercase'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('cart', 'product_item_code'), name='unique_active_cart_item'),
        ),
    ]
