# Generated by Django 5.2.4 on 2026-03-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_mysql_compatible_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this cart active? False when cart is cleared or checked out.'),
        ),
    ]
