from django.urls import path
from .views import (
    get_business_partners_list,
    get_business_partner_detail,
    policy_customer_balance_list,
    policy_customer_balance_detail,
    list_policies,
    list_db_policies,
    sync_policies,
    policy_list_page,
    warehouse_for_item_api,
    contact_persons_api,
    project_balance_api,
    customer_addresses_api,
    territories_full_api,
    cwl_full_api,
    customer_lov_api,
    item_lov_api,
    item_price_api,
    policy_items_for_customer_api,
    policy_project_link_api,
    projects_lov_api,
    crop_lov_api,
    sales_orders_api,
    sales_vs_achievement_geo_inv_api,
    sales_vs_achievement_territory_api,
    customer_policies_api,
)

urlpatterns = [
    # Unified API for Frontend - card_code is optional via two endpoints
    path('business-partner/', get_business_partners_list, name='unified_bp_api_list'),
    path('business-partner/<str:card_code>/', get_business_partner_detail, name='unified_bp_api'),
    # Policy Customer Balance - main endpoint (no card_code required)
    path('policy-customer-balance/', policy_customer_balance_list, name='policy_customer_balance_list'),
    # Legacy endpoint - card_code in path (kept for backward compatibility)
    path('policy-customer-balance/<str:card_code>/', policy_customer_balance_detail, name='policy_customer_balance_detail'),
    path('policies/', list_policies, name='sap_policies'),
    # DB-backed policies APIs and page
    path('policy-records/', list_db_policies, name='policy_records'),
    path('policies/sync/', sync_policies, name='policies_sync'),
    path('policies/view/', policy_list_page, name='policies_page'),
    path('warehouse-for-item/', warehouse_for_item_api, name='warehouse_for_item_api'),
    path('contact-persons/', contact_persons_api, name='contact_persons_api'),
    path('project-balance/', project_balance_api, name='project_balance_api'),
    path('customer-addresses/', customer_addresses_api, name='customer_addresses_api'),
    path('territories-full/', territories_full_api, name='territories_full_api'),
    path('cwl-full/', cwl_full_api, name='cwl_full_api'),
    path('customer-lov/', customer_lov_api, name='customer_lov_api'),
    path('item-lov/', item_lov_api, name='item_lov_api'),
    path('item-price/', item_price_api, name='item_price_api'),
    path('customer-policies/', customer_policies_api, name='customer_policies_api'),
    path('policy-items/', policy_items_for_customer_api, name='policy_items_for_customer_api'),
    path('policy-items-lov/', policy_items_for_customer_api, name='policy_items_lov_api'),
    path('policy-project-link/', policy_project_link_api, name='policy_project_link_api'),
    path('projects-lov/', projects_lov_api, name='projects_lov_api'),
    path('crop-lov/', crop_lov_api, name='crop_lov_api'),
    path('sales-orders/', sales_orders_api, name='sales_orders_api'),
    path('sales-vs-achievement-geo-inv/', sales_vs_achievement_geo_inv_api, name='sales_vs_achievement_geo_inv_api'),
    path('sales-vs-achievement-territory/', sales_vs_achievement_territory_api, name='sales_vs_achievement_territory_api'),
]
