# Generated by Django 5.2.4 on 2025-09-09 06:27

import django.db.models.deletion
import django_google_maps.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", django_google_maps.fields.AddressField(max_length=255)),
                (
                    "geolocation",
                    django_google_maps.fields.GeoLocationField(max_length=100),
                ),
                (
                    "size",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Size in acres/hectares",
                        max_digits=10,
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        choices=[
                            ("clay", "Clay"),
                            ("sandy", "Sandy"),
                            ("silty", "Silty"),
                            ("peaty", "Peaty"),
                            ("chalky", "Chalky"),
                            ("loamy", "Loamy"),
                        ],
                        max_length=100,
                    ),
                ),
                ("ownership_details", models.TextField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Indicates if the farm is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Soft delete timestamp", null=True
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
